### PR TITLE
enabling batch span processor metrics for quoteservice

### PR DESCRIPTION
**Pull request by brettmc**
# Changes

PHP's batch span processor can emit metrics. There is not yet an async implementation, so use react's event loop to periodically flush traces and metrics. Add a grafana chart for some of the batch span processor metrics: dropped, pending, processed, queued

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by julianocosta89 — APPROVED** [review]
LGTM.
Added the dependencies update in this PR.
Hope you don't mind!

**Review by mviitane — APPROVED** [review]
Looks good. For some reason the Recommendation service related graphs don't seem to work, but I think it's not related to this PR.
image

**Comment by julianocosta89** [comment]
> Looks good. For some reason the Recommendation service related graphs don't seem to work, but I think it's not related to this PR. image

Yeah, this dashboard looks weird TBH.
If I select `quoteservice` I wouldn't expect to see any `recommendationservice` metrics.

But not related to this PR, so I'll move on with it.

**Comment by cartersocha** [comment]
I had the same issue @julianocosta89 but apparently it was because we only had a recommendation service failure scenario previously so someone wanted to spotlight the data. but I think it’s odd too with the drop-down

**Comment by brettmc** [comment]
I didn't consider being able to choose other services when I set up that new chart.

There are no semantic conventions that I'm aware of which cover how a batch processor should emit metrics (although likely similarities between SIGs - we based our implementation on Java's). If there were then that chart could show multiple services, and the metrics would be more useful, IMO.

**Pull request merged**
