### PR TITLE
Kubernetes doc

### PR DESCRIPTION
**Pull request by cartersocha**

### CODE REVIEW

**Comment by puckpuck** [comment]
We need to add more detailed instructions on how to install the Helm chart.

- configure the OpenTelemetry collector's config for export of data (with and without Jaeger/Prometheus)
- use different service types and/or ingress routes to expose demo services
- configure the load generator to increase/decrease load

**Comment by cartersocha** [comment]
@puckpuck sounds good. I dont think I'll have the time this week. Maybe we can ask @joshleecreates or someone in the slack channel to help?

**Comment by joshleecreates** [comment]
@cartersocha I can take care of it tomorrow. @puckpuck can you provide more context for what you have in mind for collector config? Just more concrete yaml examples?

**Comment by joshleecreates** [comment]
> @cartersocha I can take care of it tomorrow. @puckpuck can you provide more context for what you have in mind for collector config? Just more concrete yaml examples?

Oh, I see that @puckpuck volunteered in Slack. Great :)

**Pull request closed without merging**
