### PR TITLE
chore: update trace based tests to test stream events

### PR DESCRIPTION
**Pull request by danielbdias**
# Changes

This PR adds more validations to the Checkout service and the Frontend service to consider the events that are produced and consumed in Kafka. With that, we can guarantee that the Accountability and Fraud Detection services are properly working and consuming orders.

Also, we are updating the trace-based tests to remove some deprecation notices about test namings definitions that changed (transactions are test suites, and environments are variable sets). 

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by julianocosta89** [comment]
Hey @danielbdias could you fix the `yamllint` issue and add a changelog?

**Comment by danielbdias** [comment]
@julianocosta89 sure! I'm adding it on commit ae153bca4e1f5503058c59182d7146b4a3069a1a .

**Review by julianocosta89 — APPROVED** [review]
LGTM

**Comment by cartersocha** [comment]
Thanks Daniel

**Pull request merged**
