### PR TITLE
Add resource detectors to product catalog service

### PR DESCRIPTION
**Pull request by svrnm**
Signed-off-by: svrnm <neumanns@cisco.com>

# Changes

Same as #676, but the product catalog service required some updates for the OpenTelemetry dependencies so I put it into a seperate PR

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs](../docs/) folder

### CODE REVIEW

**Review by julianocosta89 — APPROVED** [review]
LGTM
image

**Review by fatsheep9146 — APPROVED** [review]

**Comment by julianocosta89** [comment]
@svrnm this one should be good to go. Could you take care of the merge conflicts?

**Comment by fatsheep9146** [comment]
> @svrnm this one should be good to go. Could you take care of the merge conflicts?

I think you can also add resource detection to the metric part, which is newly added. @svrnm :)

**Comment by svrnm** [comment]
> > @svrnm this one should be good to go. Could you take care of the merge conflicts?
> 
> I think you can also add resource detection to the metric part, which is newly added. @svrnm :)

done.:)

**Pull request merged**
