### PR TITLE
Update README.md with Azure data explorer demo

### PR DESCRIPTION
**Pull request by asaharn**
# Changes

Added Azure data explorer as featured demo in readme

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by mviitane — COMMENTED** [review]
Please maintain alphabetic ordering in the table. Unfortunately, this means changes in several lines.

**Comment by mviitane** [comment]
@asaharn, you could consider waiting for #911 to be merged first to avoid merge conflicts with the table.

**Comment by asaharn** [comment]
@mviitane I have updated the change

**Review by cartersocha — APPROVED** [review]

**Comment by asaharn** [comment]
@cartersocha  Thankyou for approving. Can we merge it since all checks are pass.

**Comment by cartersocha** [comment]
Sure. Thanks for the contribution @asaharn

**Review by mviitane — APPROVED** [review]

**Pull request merged**
