### PR TITLE
[adservice] add some hints when missing port config.

### PR DESCRIPTION
**Pull request by JaredTan95**
# Changes
add default service avoid numberparse exception:

```text
Picked up JAVA_TOOL_OPTIONS: -javaagent:/app/opentelemetry-javaagent.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2022-11-30 10:09:01:173 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.16.0
2022-11-30 10:09:31 - hipstershop.AdService - AdService starting. trace_id= span_id= trace_flags= 
Exception in thread "main" java.lang.NumberFormatException: Cannot parse null string
        at java.base/java.lang.Integer.parseInt(Integer.java:630)
        at java.base/java.lang.Integer.parseInt(Integer.java:784)
        at hipstershop.AdService.start(AdService.java:61)
        at hipstershop.AdService.main(AdService.java:233)
```

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs](../docs/) folder

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

### CODE REVIEW

**Comment by julianocosta89** [comment]
Hello @JaredTan95, thanks for the contribution.

If I'm not mistaken we chose to make the service to fail in case no port is provided.

@mic-max is that right?

**Comment by JaredTan95** [comment]
> Hello @JaredTan95, thanks for the contribution.
> 
> If I'm not mistaken we chose to make the service to fail in case no port is provided.
> 
> @mic-max is that right?

If that, I would like to add some hints like `missing port configuration`. :-P

**Review by puckpuck — APPROVED** [review]

**Comment by puckpuck** [comment]
Though not consistent for all services, _most_ do report an error if the bind port is not set on startup. This change is a good thing.

**Comment by julianocosta89** [comment]
@JaredTan95 could you fix the merge conflicts, so we can get this merged?

**Review by julianocosta89 — APPROVED** [review]

**Comment by mic-max** [comment]
> Hello @JaredTan95, thanks for the contribution.
> 
> If I'm not mistaken we chose to make the service to fail in case no port is provided.
> 
> @mic-max is that right?

Yes, looks like this will just give a clearer error message, thanks for the change @jaredTan95

**Pull request merged**
