### PR TITLE
[shippingservice] add grpc conventions

### LINKED ISSUE #596: [shippingservice] improve support for grpc
# Feature Request

add proper grpc span attributes to ShippingService

**Is your feature request related to a problem?**

other services which are using auto-instrumentation for grpc properly set SpanKind, RpcSystem, and RpcGrpcStatusCode. ShippingService manually instruments grpc transactions, but doesn't set these span attributes, which can lead to loss of fidelity in some APM backends.

**Describe the solution you'd like:**

set SpanKind=SERVER, RpcSystem=grpc, name span in accordance with grpc span conventions, and set RpcGrpcStatusCode.

**Describe alternatives you've considered.**

auto-instrumentation for grpc/rust, which i don't think yet exists.

## Additional Context

PR forthcoming.

### PR DESCRIPTION
**Pull request by ty-elastic**
Fixes #596 

## Changes

* use OTEL semantic conventions where defined
* name tracer in accordance with other services which sink grpc transactions
* name span in accordance with OTEL grpc conventions
* set SpanKind to SERVER for functions sinking grpc transactions
* set RpcSystem to grpc
* Set RpcGrpcStatusCode appropriately

### CODE REVIEW

**Review by julianocosta89 — COMMENTED** [review]
@ty-elastic could you also update the docs?
https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/services/shippingservice.md

**Review by julianocosta89 — APPROVED** [review]
LGTM

**Comment by ty-elastic** [comment]
@julianocosta89, docs updated as appropriate! thanks!

**Review by julianocosta89 — APPROVED** [review]
Thanks @ty-elastic !
LGTM

**Review by austinlparker — APPROVED** [review]

**Pull request merged**
