### PR TITLE
reduce quoteservice spans

### PR DESCRIPTION
**Pull request by brettmc**
# Changes

Update slim auto-instrumentation to beta4, and remove psr-15 auto-instrumentation.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs](../docs/) folder

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

Fixes: #659

### CODE REVIEW

**Comment by cartersocha** [comment]
From 14 spans to 3 spans. Nice!

**Review by cartersocha — APPROVED** [review]
lgtm

**Comment by cartersocha** [comment]
Fix towards https://github.com/open-telemetry/opentelemetry-demo/issues/659

**Review by mviitane — APPROVED** [review]
Great improvement!

**Review by julianocosta89 — APPROVED** [review]
Awesome!

**Pull request merged**
