### PR TITLE
[frontend] fix http.status_code on error

### PR DESCRIPTION
**Pull request by puckpuck**
Fixes: #749 

The `http.status_code` for synthetic requests to the frontend, was being set at span creation time. This changes that to set it just before the span ends. Looks like the `app.frontend.requests` metric was also affected by this issue.

Also removed some duplicated error handling code.

### CODE REVIEW

**Comment by julianocosta89** [comment]
Hello @puckpuck 👋🏽 

Not sure what is going on here, maybe @martinkuba can help us out, but I've tested this change locally and I didn't get the expected result.

I've built the new frontend and manually killed the cart-service.
The error spans were still with status `200`:
image

I do get some `500`, but not all errors are correctly mapped:
image

Any thoughts?

**Comment by julianocosta89** [comment]
When testing it I started getting some errors in the logs like this:
```
frontend                 | Can not execute the operation on ended Span {traceId: 9a72857f7ceef2b0e3a7856e0856e4e7, spanId: 214218836dea381f}
frontend                 | You can only call end() on a span once.
```

Besides that, it looks good to me.

**Comment by martinkuba** [comment]
I am looking at this as well, and I am seeing the `Can not execute the operation on ended Span` error as well. It looks like it is this [line](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontend/utils/telemetry/InstrumentationMiddleware.ts#L67). It is happening on the main branch for me as well. I think it makes sense since the span is from the http instrumentation when the site is NOT running in synthetic mode. I am guessing we just never noticed this before? The fix would be to end the span manually only when it is also created in this same file.

**Comment by puckpuck** [comment]
Oh, I see. It only happens when you access the app from a browser UI (non-synthetic requests).

Yeah, I can plug in some logic to only close if we created it. Will update the PR later today.

**Comment by puckpuck** [comment]
Updated the PR to only end the span when it's the one that we create to split synthetic requests.

**Review by martinkuba — APPROVED** [review]

**Review by julianocosta89 — APPROVED** [review]
Awesome! 🤩

**Comment by cartersocha** [comment]
Can you add a changelog item please

**Pull request merged**
