### PR TITLE
[quoteservice] Replace php-cli to php-apache

### PR DESCRIPTION
**Pull request by julianocosta89**
## Changes

PHP-CLI is a PHP built-in server and should not be used in production, more info here: https://www.php.net/manual/en/features.commandline.webserver.php#features.commandline.webserver.
In order to have a service that users can relate to real life services, I've updated the QuoteService to make use of PHP-Apache.

I've also added OPcache in order to improve the PHP performance: https://www.php.net/manual/en/intro.opcache.php

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes

### CODE REVIEW

**Comment by mviitane** [comment]
Seems to be running fine. One comment though. Is it possible to fix the two first lines from the log:
```
$ docker compose logs quoteservice
quoteservice  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
quoteservice  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
quoteservice  | [Tue Nov 08 09:12:53.126646 2022] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.54 (Debian) PHP/8.1.12 configured -- resuming normal operations
quoteservice  | [Tue Nov 08 09:12:53.127943 2022] [core:notice] [pid 8] AH00094: Command line: 'apache2 -D FOREGROUND'
quoteservice  | 172.18.0.15 - - [08/Nov/2022:09:13:10 +0000] "POST /getquote HTTP/1.1" 200 167 "-" "-"
quoteservice  | 172.18.0.15 - - [08/Nov/2022:09:13:14 +0000] "POST /getquote HTTP/1.1" 200 184 "-" "-"
quoteservice  | 172.18.0.15 - - [08/Nov/2022:09:13:14 +0000] "POST /getquote HTTP/1.1" 200 169 "-" "-"
```

**Comment by julianocosta89** [comment]
> Seems to be running fine. One comment though. Is it possible to fix the two first lines from the log:
> 
> ```
> $ docker compose logs quoteservice
> quoteservice  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
> quoteservice  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
> quoteservice  | [Tue Nov 08 09:12:53.126646 2022] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.54 (Debian) PHP/8.1.12 configured -- resuming normal operations
> quoteservice  | [Tue Nov 08 09:12:53.127943 2022] [core:notice] [pid 8] AH00094: Command line: 'apache2 -D FOREGROUND'
> quoteservice  | 172.18.0.15 - - [08/Nov/2022:09:13:10 +0000] "POST /getquote HTTP/1.1" 200 167 "-" "-"
> quoteservice  | 172.18.0.15 - - [08/Nov/2022:09:13:14 +0000] "POST /getquote HTTP/1.1" 200 184 "-" "-"
> quoteservice  | 172.18.0.15 - - [08/Nov/2022:09:13:14 +0000] "POST /getquote HTTP/1.1" 200 169 "-" "-"
> ```

Good catch @mviitane, fixed!

**Review by mviitane — APPROVED** [review]
LGTM. Also the logs were fixed.

**Comment by julianocosta89** [comment]
@mviitane I've also added OPCache in order to improve the PHP performance (more added to the initial changes text).
Do you mind just double checking it on your end?

**Comment by julianocosta89** [comment]
@bobstrecansky would you be able to have a look?

**Comment by mviitane** [comment]
> @mviitane I've also added OPCache in order to improve the PHP performance (more added to the initial changes text).
> Do you mind just re-validating it?

Seems to be running fine, didn't notice any functional changes.

**Review by mviitane — APPROVED** [review]

**Pull request merged**
