### PR TITLE
[loadgenerator] start locust with host "0.0.0.0" (#1437)

### PR DESCRIPTION
**Pull request by MoZhonghua**
starts `locust` with env `LOCUST_WEB_HOST=0.0.0.0`

fix https://github.com/open-telemetry/opentelemetry-demo/issues/1437

### CODE REVIEW

**Comment by puckpuck** [comment]
Why is this change needed?

**Comment by MoZhonghua** [comment]
> Why is this change needed?

locust fails to start if ipv6 is disabled. With this env, we force locust to bind ipv4 address.

**Review by julianocosta89 — APPROVED** [review]

**Review by puckpuck — CHANGES_REQUESTED** [review]
This implementation is fine, but we should be following the pattern for the other `LOCUST_*` environment variables, which is defining them all in the .env file, and referencing them from the 2 compose files.

SIMILAR to how we LOCUST_WEB_PORT and LOCUST_HOST defined.

**Comment by MoZhonghua** [comment]
> LOCUST_WEB_PORT



> This implementation is fine, but we should be following the pattern for the other `LOCUST_*` environment variables, which is defining them all in the .env file, and referencing them from the 2 compose files.
> 
> SIMILAR to how we LOCUST_WEB_PORT and LOCUST_HOST defined.

I Can't figure out how to change 'LOCUST_WEB_HOST' in .env file, it's already defined in `.env` as `LOCUST_WEB_HOST=loadgenerator`.

I guess `LOCUST_WEB_HOST` in `.env` is used by other service to get node name (or dns name? i don't known) of `loadgenerator`, not used to tell `locust` to bind to this address.

So there are tow different things (in my guess):
- how other service find address of loadgenerator
- which ip address shoud loadgenerator bind

These two things just use same env name by coincidence.

**Comment by puckpuck** [comment]
hmmm... I see now. We did some unfortunate things with the naming of environment variables used for the frontend-proxy.

Let's get this one approved and merged. I'll create a separate issue to track fixing the frontend-proxy.

**Review by puckpuck — APPROVED** [review]

**Pull request merged**
