### PR TITLE
Forward logs from checkout service to otel collector

### PR DESCRIPTION
**Pull request by kkn**
# Changes

* Logrus log bridge used to forward go service logs to otel collector

### CODE REVIEW

**Comment by kkn** [comment]
Opened PR here by mistake rather than on the fork.

**Comment by julianocosta89** [comment]
Hey @kkn would you like to contribute this to the demo?

We would love to add logs bridge to the service, and it seems you have it there.

It would just be matter of cleaning up the PR and signing de easyCLA.

WDYT!?

**Comment by kkn** [comment]
Hey @julianocosta89, yes, I would like to contribute.
Let me test the changes on my cluster for all the Go services and raise a PR here.

**Comment by julianocosta89** [comment]
Awesome!

**Pull request closed without merging**
