### PR TITLE
Add GuanceCloud observability vendor

### PR DESCRIPTION
**Pull request by harlonhuang**
# Changes
Add GuanceCloud observability vendor
[website]: https://www.guance.one/
[opentelemetry support]: https://docs.guance.com/en/integrations/opentelemetry/

### CODE REVIEW

**Review by cartersocha — APPROVED** [review]
Lgtm. Please just sign the cla

**Comment by cartersocha** [comment]
Next time please open your prs from a personal fork so we can force update if needed before merging. 

Thanks for your contribution 😎

**Review by mviitane — APPROVED** [review]

**Comment by harlonhuang** [comment]
Locust documentation url not found, the correct link below
https://docs.locust.io/en/2.16.0/writing-a-locustfile.html

**Comment by cartersocha** [comment]
@harlonhuang please update the load generator readme link and we should be good to go. Must've been updated recently

FILE: ./src/loadgenerator/README.md
[✖] https://docs.locust.io/en/stable/writing-a-locustfile.html → Status: 404

**Review by fatsheep9146 — APPROVED** [review]

**Pull request closed without merging**
