### PR TITLE
Enable exemplar export/display support

### PR DESCRIPTION
**Pull request by jlawrienyt**
# Changes

* Ensure the collector's Prometheus endpoint produces exemplars 
* Ensure that Prometheus collects and stores exemplar data
* Ensure that Grafana will display links to exemplars from dashboards/the explore tab

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the
[docs](https://github.com/open-telemetry/opentelemetry-demo/tree/main/docs) folder

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

### CODE REVIEW

**Comment by jlawrienyt** [comment]
[Example query with exemplars in Grafana](http://localhost:8080/grafana/explore?orgId=1&left=%7B%22datasource%22:%22webstore-metrics%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22histogram_quantile%280.95,%20sum%20by%28le%29%20%28rate%28rpc_server_duration_bucket%5B5m%5D%29%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22exemplar%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

**Comment by cartersocha** [comment]
I'm not seeing the links in grafana or the symbols on the graph. Does it require tempo as a backend or configuration to point to jaeger?

**Comment by jlawrienyt** [comment]
> I'm not seeing the links in grafana or the symbols on the graph. Does it require tempo as a backend or configuration to point to jaeger?

It shouldn't require tempo; the configuration to point to jaeger (I'm assuming you mean Grafana) is part of the change in this PR.  One thing to note is that you do need to enable exemplars for each of your Prometheus queries; it's a bit buried under "Options", e.g. 
image

**Comment by jlawrienyt** [comment]
> I'm not seeing the links in grafana or the symbols on the graph. Does it require tempo as a backend or configuration to point to jaeger?

Oh, I think I found the problem: forgot to push the upgrade to the collector version.  WIll do that shortly.

**Comment by austinlparker** [comment]
> > I'm not seeing the links in grafana or the symbols on the graph. Does it require tempo as a backend or configuration to point to jaeger?
> 
> 
> 
> It shouldn't require tempo; the configuration to point to jaeger (I'm assuming you mean Grafana) is part of the change in this PR.  One thing to note is that you do need to enable exemplars for each of your Prometheus queries; it's a bit buried under "Options", e.g. 
> 
> image
> 
> 
> 
> 
> 
> 

Could we get the default queries updated to have exemplars enabled?

**Review by julianocosta89 — APPROVED** [review]
After fixing the merge conflicts, it should be good to go

**Comment by cartersocha** [comment]
thank you James! :shipit:

**Pull request merged**
