### PR TITLE
Fix #586: Pass `categories` as an input for Ad service

### LINKED ISSUE #586: Strange adservice behavior. Is it intentional?
# Bug Report

Version: `v1.1.0` / `9a66c3a7e490dc0a30c738b92d931d04ce42f479` / `main` (just plain `git clone`)

## Symptom

It seems that the request for the ad is crafted incorrectly. It results in random ads being served.

After a quick looking at the docs and scenarios it's not clear whether it's intentional or not.

**What is the expected behavior?**

Appropriate adds are served for every request.

**What is the actual behavior?**

Random ad is served for every request.

## Reproduce

1. Open any product page. E.g. "Optical Tube Assembly": http://localhost:8080/product/9SIQT8TOJO. This `9SIQT8TOJO` is a product id, right?
2. A request is seen in browser's developers console: http://localhost:8080/api/data?productIds=9SIQT8TOJO
3. This `9SIQT8TOJO` is used to query `adservice`: https://github.com/open-telemetry/opentelemetry-demo/blob/9a66c3a7e490dc0a30c738b92d931d04ce42f479/src/frontend/pages/api/data.ts#L12
4. A request arrives in `adservice`:
    ```
    ad-service               | 2022-11-15 20:57:22 - hipstershop.AdService - received ad request (context_words=[9, S, I, Q, T, 8, T, O, J, O]) trace_id=e8c29c9773b16a424d5383acb41a2f15 span_id=ecd925196c0ed6c9 trace_flags=01
    ```
    image
5. So this `9SIQT8TOJO` is treated as ten separate context words.
6. The ads map doesn't contain any ads for any of these letters: https://github.com/open-telemetry/opentelemetry-demo/blob/9a66c3a7e490dc0a30c738b92d931d04ce42f479/src/adservice/src/main/java/hipstershop/AdService.java#L221-L227
7. Thus, no ads found and the ads request falls back to the `getRandomAds` any time.
8. This is also seen in Jaeger (all the requests have a call to the `getRandomAds` at the end):
    image

## Additional Context

N/A

### PR DESCRIPTION
**Pull request by madhead**
Fixes #586.

## Changes

1. Pass `categories` as an input for Ad service
2. Randomize the ad shown, in case there are multiple ads in a response.
3. I had to bump the TS target to ES2015 to be able to use `Set`. I hope this is OK for a demo.

### CODE REVIEW

**Review by julianocosta89 — APPROVED** [review]
LGTM

**Comment by cartersocha** [comment]
@madhead please make a changelog entry and I'll merge 🚀

**Comment by madhead** [comment]
@cartersocha, done.

**Comment by puckpuck** [comment]
When I run this... spans going into the Ad service have empty `app.ads.contextKeys`.

Screen Shot 2022-11-21 at 11 27 40 PM

**Review by puckpuck — CHANGES_REQUESTED** [review]
When I run this I get empty `app.ads.contextKeys`

Screen Shot 2022-11-21 at 11 27 40 PM

**Comment by julianocosta89** [comment]
> When I run this I get empty `app.ads.contextKeys`
> 
> Screen Shot 2022-11-21 at 11 27 40 PM

@puckpuck not all of the requests:
image

**Comment by mviitane** [comment]
I also tested this and most of the time `app.ads.contextKeys` is empty. I'd assume this is not how it should be.

**Comment by madhead** [comment]
@mviitane , @julianocosta89, @puckpuck

I agree, I saw those empty requests too, but didn't address them here.

I'm not an React expert, but the bigger problem here, IMO, is that [`AdProvider`](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontend/providers/Ad.provider.tsx) provides not only ads, but recommendations too, violating single responsibilities principle. But wherever it is used, both ads and recommendations are requested.

Looking at three usages of this provider:

1. https://github.com/open-telemetry/opentelemetry-demo/blob/90964205fd37a3dbd8d36b9d7362590ced4bc818/src/frontend/pages/cart/index.tsx#L17-L25
    Cart only uses recommendations.
2. https://github.com/open-telemetry/opentelemetry-demo/blob/32d1ee681042e55cb2c360d918a4928de50325c2/src/frontend/pages/product/%5BproductId%5D/index.tsx#L51-L84
    Product page uses both [ads](https://github.com/open-telemetry/opentelemetry-demo/blob/32d1ee681042e55cb2c360d918a4928de50325c2/src/frontend/pages/product/%5BproductId%5D/index.tsx#L81) and [recommendations](https://github.com/open-telemetry/opentelemetry-demo/blob/32d1ee681042e55cb2c360d918a4928de50325c2/src/frontend/pages/product/%5BproductId%5D/index.tsx#L79).
3. https://github.com/open-telemetry/opentelemetry-demo/blob/90964205fd37a3dbd8d36b9d7362590ced4bc818/src/frontend/pages/cart/checkout/%5BorderId%5D/index.tsx#L19-L43
    Order page uses both [ads](https://github.com/open-telemetry/opentelemetry-demo/blob/90964205fd37a3dbd8d36b9d7362590ced4bc818/src/frontend/pages/cart/checkout/%5BorderId%5D/index.tsx#LL40) and [recommendations](https://github.com/open-telemetry/opentelemetry-demo/blob/90964205fd37a3dbd8d36b9d7362590ced4bc818/src/frontend/pages/cart/checkout/%5BorderId%5D/index.tsx#L38).

In some of this contexts the categories are inherently empty.

I would say, this should be fixed and split into two different provider components.

But, I could just "short-circuit" this call, what do you think? Like put a check, a guard clause, "if the categories are empty, then just return empty list of adds". Or something similar to remote this unneeded call. A dirty hack, but should work.

Would it be ok?

**Comment by madhead** [comment]
I totally forgot about the load generator. It might be sending incorrect requests too. I've added both fixes, please check the PR now (beware of the cached images!).

**Comment by cartersocha** [comment]
@austinlparker we should test the build time increase from 3 new containers. One thing to keep in mind is that go doesn’t have an operator instrumentation option. We’d need to implement that with the Java service or replace Go

**Comment by cartersocha** [comment]
For the architecture docs and services table my bias would be to label the language Java not Kotlin for the fraud detection service

**Comment by julianocosta89** [comment]
@cartersocha I think your comments are regarding #457, and not this one😅

**Comment by cartersocha** [comment]
Lol the perils of mobile bulk reviews @julianocosta89. Thanks

**Review by julianocosta89 — APPROVED** [review]
After the update we always get a context.

**Review by puckpuck — APPROVED** [review]
Confirmed this provides proper context keys on all requests types.

**Pull request merged**
