### PR TITLE
Add Logz.io to 'Demos featuring the Astronomy Shop' listing on README.md

### PR DESCRIPTION
**Pull request by horovits**
Adding Logz.io to the 'Demos featuring the Astronomy Shop' listing. Inserted per alphabetical order.
Link provided with reference.

# Changes

inserted a line item for Logz.io per alphabetical order to the 'Demos featuring the Astronomy Shop' listing

### CODE REVIEW

**Comment by cartersocha** [comment]
Please reopen from a personal fork so we can update the branch. 

Thanks for your contribution and demo promotion!

**Comment by horovits** [comment]
> Please reopen from a personal fork so we can update the branch.
> 
> Thanks for your contribution and demo promotion!

@cartersocha do you mean I cannot submit a pull request from the logzio github account? can you help clarify the constraints? 
Thanks, and happy to keep promoting the demo 😄

**Comment by cartersocha** [comment]
Yes due to branch protections on enterprise accounts we can't update your branch. We just merged 2 PRs so your branch is out of date but only you have permissions to click update. 

If you could fork from your personal github account and re-open that would be helpful. Then we can update it as needed which makes maintainer lives easier 😄

**Comment by julianocosta89** [comment]
@horovits you can also click to update the branch, and we will merge it when it is up-to-date.
Sending from a personal fork makes everyone's life easier, because maintainers can also update your branch.

**Review by mviitane — APPROVED** [review]

**Comment by horovits** [comment]
@julianocosta89 @cartersocha makes sense, I just did it via the corp account as it pertains to the company's support of the demo, but didn't know it'd complicate things :-) 
anyway I clicked to update the branch, now pending maintainer approval post merge, hope this puts us in the clear for this one 👍

**Pull request merged**
