### PR TITLE
Major version update (version 2.0.0) for OTel Java instrumentation

### PR DESCRIPTION
**Pull request by mviitane**
Major version update (version 2.0.0) for OTel Java instrumentation for
`adservice, frauddetectionservice, kafka
`

The new Java instrumentation uses HTTP as the default export protocol. This PR changes the Java services to export HTTP instead of gRPC.

The new Java instrumentation introduces a lot of kafka.consumer.* metrics from frauddetectionservice.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by puckpuck — APPROVED** [review]

**Review by julianocosta89 — APPROVED** [review]
LGTM

**Comment by julianocosta89** [comment]
@mviitane with this update on the env vars we will have to adjust the Helm chart.
https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo
Would you also be able to take care of it?

**Comment by julianocosta89** [comment]
actually, maybe we can wait the 3 PRs to get merged and so 1 update on the charts.

I'm just going over them

**Comment by mviitane** [comment]
> actually, maybe we can wait the 3 PRs to get merged and so 1 update on the charts.

Yes, I agree.

**Pull request merged**
