### PR TITLE
prep for 1.7 release

### PR DESCRIPTION
**Pull request by austinlparker**

### CODE REVIEW

**Review by mviitane — APPROVED** [review]

**Comment by julianocosta89** [comment]
Should we wait for #1297 to get fixed?

**Comment by puckpuck** [comment]
> Should we wait for #1297 to get fixed?

Yes

**Comment by austinlparker** [comment]
Are we good then since the PR was reverted?

**Comment by puckpuck** [comment]
Let's merge this in the morning, so we can release and get Helm done immediately.

**Pull request merged**
