### PR TITLE
Added support for baggage read and Set as attributes, added sdk builders and Semantic changes

### LINKED ISSUE #52: Review and enhance tracing support for currency service (C++)
The following is a list of requirements that we need to evaluate before declaring v1 for trace telemetry. These requirements are across the entire application; Not all services will meet all requirements. Determine the relevant features for this service. 

- [x] Automatic Instrumentation is being used where appropriate.
- [x] Library instrumentation is being used if automatic instrumentation is unavailable.
- [ ] Services extend automatic instrumentation.
  - [x] New attributes/events attached to existing spans.
  - [x] New spans are being created from existing spans.
- [x] Automatic and Manual Context Propagation are being demonstrated.
- [x] Telemetry is not being sampled upfront.
- [x] Telemetry is not being filtered upfront.
- [ ] Baggage is being set and read appropriately (i.e., baggage must be explicitly set as attributes on spans)
- [ ] Update the [centralized tracing doc](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/trace_service_features.md)

Referencing: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/42

Service: https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/main/src/currencyservice/README.md

C++ dependent on this item: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/36

### PR DESCRIPTION
**Pull request by DebajitDas**
Fixes #52

## Added support for baggage read and Set as attributes, added sdk builders and Semantic changes.

The baggage support is added with the assumption that baggage is expected in the header with key as "baggage" and value as string. There can be changes on this if the assumption is not correct.

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by lalitb — APPROVED** [review]
Thanks.

**Comment by cartersocha** [comment]
We've talked about adding session Id & some other baggage values. 

Is this creating a new baggage item? 

@austinlparker @puckpuck do we want services creating new baggage items or just reading the upstream baggage? We might need to change the requirements

**Comment by puckpuck** [comment]
We aren't expecting the currency service to set anything in baggage. I think the frontend and/or checkout will add baggage that is read by downstream services.

**Comment by cartersocha** [comment]
@DebajitDas if you can update the change log I will merge

**Comment by DebajitDas** [comment]
> @DebajitDas if you can update the change log I will merge

Updated @cartersocha

**Comment by cartersocha** [comment]
Small lint error @DebajitDas

**Comment by DebajitDas** [comment]
> Small lint error @DebajitDas

The PR is ready to be merged now. @cartersocha

**Pull request merged**
