### PR TITLE
Remove redundant components from collector config

### PR DESCRIPTION
**Pull request by dmitryax**
`metrics/spanmetrics` pipeline is not being used. Removing it along with unused `otlp/spanmetrics` receiver.

### CODE REVIEW

**Comment by puckpuck** [comment]
The spanmetrics processor/receiver combo is used in the demo and exports data into Prometheus.  This is a screenshot with some of the metrics it generates

The spanmetrics processor is absolutely being used in the demo.  This is a screenshot of some of the metrics it generates in Grafana.
Screen Shot 2022-11-02 at 8 27 20 PM

This brings up a new issue we should add, which is putting charts with these metrics into the main demo dashboard we ship in Grafana.  I'll go ahead and close the PR, and create a new Issue to add charts with these metrics.

**Comment by dmitryax** [comment]
@puckpuck can you explain why this pipeline is needed for and make sure the dashboard doesn't work without it before closing the PR?

**Comment by dmitryax** [comment]
cc @demo-approvers

**Comment by dmitryax** [comment]
cc @open-telemetry/demo-approvers

**Comment by puckpuck** [comment]
I think I missed this the first time through.  This removes everything but the processor itself, and uses the prometheus metrics pipeline instead of the otlp/spanmetrics one.

**Review by puckpuck — APPROVED** [review]
I tried this config in K8s and it works as expected.

**Review by austinlparker — APPROVED** [review]
lgtm on local

**Pull request merged**
