### PR TITLE
Add session ID attribute to frontend spans

### PR DESCRIPTION
**Pull request by martinkuba**
# Changes

This adds back the `app.session.id` span attribute that was originally handled in the Go frontend server. The attribute is added for browser spans as well as some spans from the frontend server.

Resolves https://github.com/open-telemetry/opentelemetry-demo/issues/758

### CODE REVIEW

**Comment by cartersocha** [comment]
Please add a changelog item too when you get a chance

**Review by cartersocha — APPROVED** [review]
lgtm

**Comment by cartersocha** [comment]
Should we note this only appears on non-synthetic requests in our docs? @open-telemetry/demo-approvers 

Also maybe it's just me but I find front-end, front-end-web, and front-end-proxy confusing. Might be worth re-naming one of the user facing services or the synthetic pair. I'd expect to see my user generated traces in the general front-end bucket but you have to go to another service that starts reporting post website interaction

**Review by julianocosta89 — CHANGES_REQUESTED** [review]
Where is the `app.session.id` supposed to be?
I've re-built the sample, started it, stopped the loadgen, and accessed the frontend manually.
When navigating through the generated spans, I could only find the `id` as part of the `http.url` and there was no `app.session.id` attribute, as we can see in the screenshot below:
Screenshot from 2023-03-17 07-24-23

Am I missing something?

**Comment by cartersocha** [comment]
@julianocosta89 it only shows on user generated traces rn. See my comments above

**Comment by julianocosta89** [comment]
@cartersocha I stopped the loadgen and navigated manually.

**Comment by martinkuba** [comment]
@julianocosta89 I have pulled down the codebase to a different directory, rebuilt from my branch, and I am seeing the `app.session.id` attribute there.

image

@cartersocha Are you seeing this on your end?

**Review by julianocosta89 — APPROVED** [review]
Thanks @martinkuba!
Looks like I did something wrong. Re-built it again and now it worked.

LGTM!

**Comment by cartersocha** [comment]
Please add the changelog item and we're ready to merge!

**Pull request merged**
