### PR TITLE
feat: propagate cartservice exceptions

### PR DESCRIPTION
**Pull request by rogercoll**
# Changes

Propagate Grpc expections; the `EmptyCart` method already sets the error in the span, but these two other methods aren't. A common propagated error is when the service cannot establish a connection with the Valkey database.

## Merge Requirements

For new features contributions, please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
~~* [] Appropriate documentation updates in the [docs][]~~
~~* [ ] Appropriate Helm chart updates in the [helm-charts][]~~

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by julianocosta89** [comment]
Not sure if this is a local issue, but it seems `cartServiceFailure` is not working at all.
I've tested the PR and I didn't get any error on the `cartService`, but then I've built main and it also didn't work.

I assume we have an error on the FF itself.

**Comment by julianocosta89** [comment]
@rogercoll, I've done some tests here and I don't see what this PR is actually changing 🤔 
On the left I have the build from this PR, on the right I have the build from main.

image

**Comment by rogercoll** [comment]
@julianocosta89 This PR should be propagating the "EmptyCart" error you are sharing in the screenshot but for the GetCart and AddItem transactions/methods. EmptyCart somehow already had it.

I have tested this PR in a scenario where the "valkey" database becomes unavailable (Crashloopback in k8s) after some minutes the Demo has started. But the PR is not tied to this specific scenario, in fact, any error that happens downstream those methods will be recorded in the transaction.

**Review by julianocosta89 — APPROVED** [review]
Thx for clarifying @rogercoll!
LGTM 
image

**Review by julianocosta89 — APPROVED** [review]

**Review by julianocosta89 — APPROVED** [review]

**Pull request merged**
