### PR TITLE
added more demo screenshots

### PR DESCRIPTION
**Pull request by saurabhdes**
## Changes

Added links to few more demo screenshots so newcomers to OpenTelemetry and new users of opentelemetry-demo will know in advance what to expect when they go to the different url's mentioned [here](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/docker_deployment.md#verify-the-webstore--the-telemetry) after deploying opentelemetry-demo . Specifically:

- Added Jaeger System Architecture screenshot, which is built dynamically by Jaeger via the traces.
- Added Prometheus UI screenshot, with one metric as an example.
- Added Grafana UI screenshot with Prometheus and Jaegar as data sources.
- Added Feature Flag UI screenshot
- Added Load Generator UI (Locust UI) screenshot

The links to the screenshot are derived from this PR comment - https://github.com/open-telemetry/opentelemetry-demo/pull/456#issuecomment-1282709798

For significant contributions please make sure you have completed the following items:

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #

### CODE REVIEW

**Comment by julianocosta89** [comment]
Just quoting @reyang here:
https://github.com/open-telemetry/opentelemetry-demo/pull/405#issuecomment-1270639863

>Given we don't intend to make modifications on these images, I wonder if they should be kept out of the repo (so we don't need to keep these binaries in the history), and only referenced in the markdown files using some permanent links.
For example, all the images in this doc works fine without having to be part of the repo https://github.com/open-telemetry/opentelemetry-cpp/blob/79a9471f5c6462cf5d013331e91f25455f824cd2/examples/prometheus/README.md.

If you drag and drop the image in a comment, GitHub will generate a link to the file, you can simply use the link in the docs, avoiding adding the binary to the repo.

**Comment by saurabhdes** [comment]
thanks @julianocosta89 . I will add the images in a comment in this PR and use that in this PR. Will update later today.

**Comment by saurabhdes** [comment]
Adding pics in this comment which i will refer to in this PR. 

JaegerUISystemArchitecture

Prometheus

GrafanaDataSourceIsPrometheus

GrafanaDataSourceIsJaeger

FeatureFlagUI

LoadGeneratorUI

**Comment by saurabhdes** [comment]
@julianocosta89 - As requested i added links to images.

**Comment by saurabhdes** [comment]
> Looks awesome to me!
> 
> 
> 
> One minor thing - the Prometheus screenshot seems very wide, maybe better to reduce the width of the window (so that the text looks bigger)?
> 
> 
> 
> https://user-images.githubusercontent.com/47896520/196496292-5c8bda8a-3a6a-4043-b892-7e208e0bd415.png

Good suggestion @reyang , will update PR

**Comment by saurabhdes** [comment]
@reyang Updated the PR.

**Review by reyang — APPROVED** [review]
Looks awesome to me 👍

**Pull request merged**
