### PR TITLE
[currencyservice] Add OTLP logs

### PR DESCRIPTION
**Pull request by julianocosta89**
# Changes

This PR adds OTLP logs to the Currency Service.

As we are using `service.version` to create metrics, I've adapted the logic in order to fetch it from env var, so we keep it updated to the latest release. The version value was not updated since `1.3.0`.

### Issues to investigate
- Once I've added the logger, no logs were printed to the terminal anymore.
- I wasn't able to make the OpenSearch/Grafana visualisation to work for those logs, but I've tested in Datadog and they are arriving properly populated. I also tested with otecol debug and it is all fine. **I need an extra hand from someone that knows how OpenSearch works.**

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs][]
* [x] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by austinlparker** [comment]
So, interesting, I do see that logs are being emitted by the service and getting picked up by the collector, but I don't see them in opensearch at all.

**Comment by julianocosta89** [comment]
> So, interesting, I do see that logs are being emitted by the service and getting picked up by the collector, but I don't see them in opensearch at all.

I've pointed the logs to Datadog and I was able to see it there properly enriched:
image

**Comment by puckpuck** [comment]
@julianocosta89 I made a small update to your PR to fix Grafana so it can find the logs emitted by the C++ SDK and all other services.

From my testing, this works.

**Review by puckpuck — APPROVED** [review]

**Comment by julianocosta89** [comment]
> @julianocosta89 I made a small update to your PR to fix Grafana so it can find the logs emitted by the C++ SDK and all other services.
> 
> From my testing, this works.

Thank you @puckpuck!

image

**Pull request merged**
