### PR TITLE
Fix flaky cartservice build

### PR DESCRIPTION
**Pull request by austinlparker**
testing to see if updating builder fixes cartservice build failures on GHA

### CODE REVIEW

**Comment by austinlparker** [comment]
This is ready for review - couple of notes on the process:

My goal with this PR is to resolve the following build error that cropped up after the updates to .net7:

```
 > [linux/arm64 builder 5/5] RUN   RUNTIME_IDENTIIFER=linux-musl-x64;   if [ "$(uname -m)" = "aarch64" ]; then RUNTIME_IDENTIIFER=linux-musl-arm64; fi;   dotnet restore ./src/cartservice.csproj -r $RUNTIME_IDENTIIFER &&   dotnet publish ./src/cartservice.csproj -p:PublishSingleFile=true -r $RUNTIME_IDENTIIFER --self-contained true -p:PublishTrimmed=False -p:TrimMode=Link -c Release -o /cartservice --no-restore:
21.25   Determining projects to restore...
56.39   Restored /usr/src/app/src/cartservice.csproj (in 30.06 sec).
63.50 MSBuild version 17.6.8+c70978d4d for .NET
157.2   cartservice -> /usr/src/app/src/bin/Release/net7.0/linux-musl-arm64/cartservice.dll
160.5 /usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error MSB4018: The "ReadStaticWebAssetsManifestFile" task failed unexpectedly. [/usr/src/app/src/cartservice.csproj]
160.5 /usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/usr/src/app/src/cartservice.csproj]
160.5 /usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error MSB4018:    at InvokeStub_ReadStaticWebAssetsManifestFile.set_ManifestPath(Object, Object, IntPtr*) [/usr/src/app/src/cartservice.csproj]
160.5 /usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [/usr/src/app/src/cartservice.csproj]
160.5 /usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,40): error MSB4026: The "ManifestPath=$(StaticWebAssetBuildManifestPath)" parameter for the "ReadStaticWebAssetsManifestFile" task is invalid. [/usr/src/app/src/cartservice.csproj]
160.5 /usr/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error MSB4063: The "ReadStaticWebAssetsManifestFile" task could not be initialized with its input parameters.  [/usr/src/app/src/cartservice.csproj]```

This error appeared only during `amd64` builds, and it wasn't easily reproducible - nor is it an error I can find any evidence of anyone else running into. I surmise that there is a particular bug in the .NET SDK in this particular build environment under QEMU (this would certainly not be the first time we've seen strange issues with QEMU).

This PR makes the following changes to alleviate the issue:
1. Update QEMU by pulling main from the QEMU action
2. Take the most recent .NET security updates
3. Disable Static Web Assets and Reference Assemblies

Static web assets aren't necessary for cartservice (because there aren't any, it's an API-only project) and reference assemblies also aren't necessary (because they're included in the runner image).

**Review by cartersocha — APPROVED** [review]
Lgtm. 

@danielbdias I noticed this message popping up in the logs. Is there a way to turn this off? 
"WARN[0000] The "TRACETEST_DEV" variable is not set. Defaulting to a blank string. "

**Comment by austinlparker** [comment]
lmao welp

**Comment by austinlparker** [comment]
I think I might have found something useful though - https://github.com/dotnet/sdk/issues/27190

**Comment by austinlparker** [comment]
I'm looking through this issue (https://github.com/dotnet/dotnet-docker/issues/4388) which seems to indicate that this should be working on .NET 7.0.3xx (which we're on), but I'm not entirely sure if there's something we need to do in the Dockerfile to get it to reliably build.

**Comment by austinlparker** [comment]
Ok, this fix works more than it fails, so I'm gonna go ahead and merge this with the increased debug info left on so we can try to diagnose it better when it happens again.

**Pull request merged**
