### PR TITLE
update quoteservice for php Release Candidate

### PR DESCRIPTION
**Pull request by brettmc**
# Changes

- update dependencies to use RC1 and latest versions of other packages
- update code to work with RC1
- refactor Dockerfile to allow local dev, and document how

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]

**Review by julianocosta89 — APPROVED** [review]
LGTM 🚀 

@brettmc do we have logs on PHP already?

**Comment by brettmc** [comment]
> do we have logs on PHP already?

As in, via the otel logging signal? No. I'm happy to add it to this PR though - then we'll be emitting all 3 signals.

**Comment by julianocosta89** [comment]
That would be awesome!

**Review by julianocosta89 — APPROVED** [review]
Awesome!

```
otel-col                 | 2023-09-15T09:01:47.365Z	info	LogsExporter	{"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 1, "log records": 2}
otel-col                 | 2023-09-15T09:01:47.365Z	info	ResourceLog #0
otel-col                 | Resource SchemaURL: 
otel-col                 | Resource attributes:
otel-col                 |      -> service.namespace: Str(opentelemetry-demo)
otel-col                 |      -> service.name: Str(quoteservice)
otel-col                 |      -> container.id: Str(3e316009f73779851ba0eea70b89d6a3ad2a0eda519dd4da4ac4c7d3660582e0)
otel-col                 |      -> service.version: Str(1.0.0+no-version-set)
otel-col                 |      -> telemetry.sdk.name: Str(opentelemetry)
otel-col                 |      -> telemetry.sdk.language: Str(php)
otel-col                 |      -> telemetry.sdk.version: Str(1.0.0RC1)
otel-col                 |      -> telemetry.auto.version: Str(1.0.0RC1)
otel-col                 |      -> process.runtime.name: Str(cli)
otel-col                 |      -> process.runtime.version: Str(8.2.10)
otel-col                 |      -> process.pid: Int(7)
otel-col                 |      -> process.executable.path: Str(/usr/local/bin/php)
otel-col                 |      -> process.command: Str(public/index.php)
otel-col                 |      -> process.command_args: Slice(["public/index.php"])
otel-col                 |      -> process.owner: Str(www-data)
otel-col                 |      -> os.type: Str(linux)
otel-col                 |      -> os.description: Str(6.2.0-32-generic)
otel-col                 |      -> os.name: Str(Linux)
otel-col                 |      -> os.version: Str(#32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2)
otel-col                 |      -> host.name: Str(3e316009f737)
otel-col                 |      -> host.arch: Str(x86_64)
otel-col                 | ScopeLogs #0
otel-col                 | ScopeLogs SchemaURL: 
otel-col                 | InstrumentationScope slim-app 
otel-col                 | LogRecord #0
otel-col                 | ObservedTimestamp: 2023-09-15 09:01:44.492475136 +0000 UTC
otel-col                 | Timestamp: 2023-09-15 09:01:44.491661 +0000 UTC
otel-col                 | SeverityText: INFO
otel-col                 | SeverityNumber: Info(9)
otel-col                 | Body: Str(Calculated quote)
otel-col                 | Attributes:
otel-col                 |      -> context: Map({"total":124.6})
otel-col                 | Trace ID: 1b7ca10115847d1e068fda10adee737d
otel-col                 | Span ID: feb63024d02920c3
otel-col                 | Flags: 1
otel-col                 | LogRecord #1
otel-col                 | ObservedTimestamp: 2023-09-15 09:01:47.266915072 +0000 UTC
otel-col                 | Timestamp: 2023-09-15 09:01:47.266884 +0000 UTC
otel-col                 | SeverityText: INFO
otel-col                 | SeverityNumber: Info(9)
otel-col                 | Body: Str(Calculated quote)
otel-col                 | Attributes:
otel-col                 |      -> context: Map({"total":44.5})
otel-col                 | Trace ID: 325ed6dafd24c9f0556bef34b6422a3c
otel-col                 | Span ID: f10fbd07aab7b428
otel-col                 | Flags: 1
otel-col                 | 	{"kind": "exporter", "data_type": "logs", "name": "logging"}
```

**Comment by julianocosta89** [comment]
@brettmc I've just added `OTEL_PHP_INTERNAL_METRICS_ENABLED=true` to `docker-compose.minimal` as well.

**Comment by brettmc** [comment]
> Awesome!

Are you able to confirm if the detected container ID is correct? I've just applied a fix in the latest container detector package, which I've been struggling to test in k8s.

**Comment by julianocosta89** [comment]
I'm not running in k8s, but with Docker it is working fine:
image

**Pull request merged**
