### PR TITLE
Drop docs folder and adjust links

### LINKED ISSUE #729: Drop docs folder as step in migration to OTel website
For the broader context see:

- https://github.com/open-telemetry/opentelemetry.io/issues/2269

/label documentation

### PR DESCRIPTION
**Pull request by chalin**
# Changes

- Closes #729

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] (N/A) Appropriate documentation updates in the [docs][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the [@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Comment by cartersocha** [comment]
We should keep the otel image for the main readme but maybe just create another folder. Otherwise lgtm

**Review by cartersocha — APPROVED** [review]

**Comment by cartersocha** [comment]
thanks for making these changes @chalin

**Review by mviitane — APPROVED** [review]
LGTM. Just don't merge this before
https://github.com/open-telemetry/opentelemetry.io/pull/2270

**Review by julianocosta89 — APPROVED** [review]

**Review by fatsheep9146 — APPROVED** [review]

**Comment by chalin** [comment]
> We should keep the otel image for the main readme but maybe just create another folder. Otherwise lgtm

@cartersocha - would it be ok to address this separately? (We have at least two options, the details of which I'd rather discuss in the context of a followup PR or issue.)

**Comment by chalin** [comment]
> LGTM. Just don't merge this before [open-telemetry/opentelemetry.io#2270](https://github.com/open-telemetry/opentelemetry.io/pull/2270)

- Could one of y'all formally approve https://github.com/open-telemetry/opentelemetry.io/pull/2270?
- In terms of merge order, this can land first since the [demo docs are already hosted on the website](https://opentelemetry.io/docs/demo/). Deleting them from this repo won't impact the git submodule being referenced by the OTel website, but it will prevent folks from attempting to make changes to the docs in this repo.

**Comment by chalin** [comment]
@mviitane ☝️

**Comment by chalin** [comment]
Thanks for the approval of https://github.com/open-telemetry/opentelemetry.io/pull/2270 @julianocosta89!

**Comment by julianocosta89** [comment]
Thank you for this @chalin!

**Pull request merged**
