### PR TITLE
🐛 [CurrencyService] Fixing the currency service port

### PR DESCRIPTION
**Pull request by xoscar**
## Changes

When updating the entry point section for the currency service the port wasn't being sent to the server code correctly, causing an error on the services dependent on this service.

For significant contributions please make sure you have completed the following items:

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #

### CODE REVIEW

**Review by puckpuck — APPROVED** [review]
This fix seems to be reverting #292 

Looks like environment variable expansion doesn't work when ENTRYPOINT is used in shell form. /cc @lalitb

**Comment by puckpuck** [comment]
@xoscar please update this branch so we can merge it

**Comment by xoscar** [comment]
@puckpuck done 😄

**Comment by lalitb** [comment]
#296 was supposed to fix the port issue.

**Pull request merged**
