### PR TITLE
Add ads served counter metric with request and response types

### PR DESCRIPTION
**Pull request by jlawrienyt**
# Changes

Add a new counter to track the number of ad requests along with whether the request is targeted or not with context keys, and whether or not the response is targeted or random.  This fulfills some of #73.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs](../docs/) folder

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

### CODE REVIEW

**Review by julianocosta89 — APPROVED** [review]
LGTM, I would just like to test it out whenever #656 gets merged.

**Comment by jlawrienyt** [comment]
I had some questions on some of the requirements in #73.  Can post in slack also if that'd be the more appropriate place.

1. `Services should use push metrics where possible.`  Is this just using the OTLP exporter for metrics?
2. `Collectors should perform metric transforms to normalize resource and service metrics.` Not sure what this was driving at

**Comment by julianocosta89** [comment]
@cartersocha may have some insights about it

**Comment by cartersocha** [comment]
The original requirements were created when metrics weren’t widely supported and mostly based off the spec. The requirements are probably worth revisiting in general. 

In my mind we’d like at least multiple manual instrument types, trace exemplars, views, instrumentation libraries, regular attribute enrichment, and resource attribute enrichment. 

What do y’all think? 

I think the collector service / resource line poorly refers to resource enrichment haha.

**Comment by jlawrienyt** [comment]
> In my mind we’d like at least multiple manual instrument types, trace exemplars, views, instrumentation libraries, regular attribute enrichment, and resource attribute enrichment.

Just to clarify a few things: by instrumentation libraries do you mean auto-instrumentation libraries providing metrics?  And for resource attribute enrichment, I believe resource attributes can only be set when initializing the sdk, so do you mean adding more resource attributes beyond what might be auto-configured (also that would seem to apply beyond metrics, to all signal types)?  

Otherwise, I think the list looks good.

**Comment by cartersocha** [comment]
Yes those. Auto instrumentation is a fraught topic given all the flavors and can mean many things. There's agent or injection based auto instrumentation like in Python-Java / Dotnet and general instrumentation libraries. 

We probably want to separate those as distinct features in the feature matrix besides just saying instrumentation libraries? 

Agent based metrics / traces vs. instrumentation libraries added to a provider? 

Resource detectors like severin has been [adding](https://github.com/open-telemetry/opentelemetry-demo/pull/677). They need to be added to both providers (if available)

**Comment by julianocosta89** [comment]
I like it!
image

**Comment by jlawrienyt** [comment]
> Yes those. Auto instrumentation is a fraught topic given all the flavors and can mean many things. There's agent or injection based auto instrumentation like in Python-Java / Dotnet and general instrumentation libraries.
> 
> We probably want to separate those as distinct features in the feature matrix besides just saying instrumentation libraries?
> 
> Agent based metrics / traces vs. instrumentation libraries added to a provider?

Maybe the distinction between auto vs manual for instrumentation libraries is not so important, at least in terms of the feature matrix.

BTW, looks like your last PR overwrite the metrics table with trace info; going to revert that in this PR and attempt to update the columns to capture this dicussion.

**Comment by cartersocha** [comment]
thanks for catching that @jlawrienyt !  lgtm after resolving the conflict and thanks for the contribution 🚀

**Pull request merged**
