### PR TITLE
Add browser traffic in loadgenerator and export traces in frontend

### PR DESCRIPTION
**Pull request by jordibisbal8**
# Changes

In this PR, we aim to add browser traffic using playwright (as discussed https://github.com/open-telemetry/opentelemetry-demo/issues/1164). This PR should now solve the issue commented [here](https://github.com/open-telemetry/opentelemetry-demo/issues/1303) that exports the traces for the frontend-web correctly. The main changes are:

- Installed playwright in the DockerFile
- Increase memory constraints for the load generator container to be able to run playwright for several concurrent users
- Added playwright user and two tasks in the locustfile. One goes to the /cart page and the others adds a product to the cart
- Added environment variable to enable browser traffic (false by default)
- Increased delay interval in milliseconds between two consecutive exports using `scheduledDelayMillis`

**Update:** Locust generates traffic by using the baggage header `synthetic_request=true`. By doing this, the frontend can correctly export the traces using the `OTEL_COLLECTOR_NAME` endpoint instead of using the not available localhost.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs][]
* [x] Appropriate Helm chart updates in the [helm-charts][https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1014]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by julianocosta89** [comment]
Hello @jordibisbal8,

I think I'm missing something here.
I've fetched your PR, re-built the loadgen and frontend, set the env var `LOCUST_BROWSER_TRAFFIC_ENABLED=true` and started the demo.
Waited some traffic and didn't get the service `frontend-web` in Jaeger.

When I manually navigated to the browser, I got it.

Did I miss something or am I understanding the PR wrongly?

**Comment by jordibisbal8** [comment]
> Waited some traffic and didn't get the service `frontend-web` in Jaeger.

No, that should work. However, I am trying it out with NR as our vendor. I will try to do it with Jaeger then. 
Just to verify, are you correctly seeing the browser traffic events in the locust UI?

**Comment by jordibisbal8** [comment]
> Hello @jordibisbal8,
> 
> I think I'm missing something here. I've fetched your PR, re-built the loadgen and frontend, set the env var `LOCUST_BROWSER_TRAFFIC_ENABLED=true` and started the demo. Waited some traffic and didn't get the service `frontend-web` in Jaeger.
> 
> When I manually navigated to the browser, I got it.
> 
> Did I miss something or am I understanding the PR wrongly?

@danielgblanco helped me figure out the issue. We were testing it for k8s, where we use `OTEL_COLLECTOR_NAME` in the frontend code. However, it seems that for docker this variable does not exist.

**Comment by puckpuck** [comment]
I tested your branch and got what I expected using a local docker compose deployment.

I really like the usage of the `synthetic_request` baggage element to drive which Collector to output to.

**Review by puckpuck — APPROVED** [review]

**Comment by julianocosta89** [comment]
@jordibisbal8 sorry for being the picky one 😅 

I've tested and now I can see the frontend-web spans, but even though the you are setting the synthetic_request headers, you are not setting the span attributes and `app.synthetic_request` is set to `false`.

Would you be able to take a look?

Screenshot 2024-01-29 at 11 47 31

**Comment by jordibisbal8** [comment]
> app.synthetic_request

No problem. Now that you mention it,  I can see this happening as well. It is quite interesting since if I add a log in [here](https://github.com/open-telemetry/opentelemetry-demo/blob/120381acff5efaa48317abb7dd6e61cfe7340687/src/frontend/utils/telemetry/InstrumentationMiddleware.ts#L24) and I use only browser traffic (1 user), I can see the request entering the if condition, which should set the appropriate spans 🤔

**Comment by jordibisbal8** [comment]
> @jordibisbal8 sorry for being the picky one 😅
> 
> I've tested and now I can see the frontend-web spans, but even though the you are setting the synthetic_request headers, you are not setting the span attributes and `app.synthetic_request` is set to `false`.
> 
> Would you be able to take a look?
> 
> Screenshot 2024-01-29 at 11 47 31

No problem. Now that you mention it,  I can see this happening as well. It is quite interesting since if I add a log in [here](https://github.com/open-telemetry/opentelemetry-demo/blob/120381acff5efaa48317abb7dd6e61cfe7340687/src/frontend/utils/telemetry/InstrumentationMiddleware.ts#L24) and I use only browser traffic (1 user), I can see the request entering the if condition, which should set the appropriate spans 🤔

**Comment by jordibisbal8** [comment]
> > @jordibisbal8 sorry for being the picky one 😅
> > I've tested and now I can see the frontend-web spans, but even though the you are setting the synthetic_request headers, you are not setting the span attributes and `app.synthetic_request` is set to `false`.
> > Would you be able to take a look?
> > Screenshot 2024-01-29 at 11 47 31
> 
> No problem. Now that you mention it, I can see this happening as well.
> 
> After investigating it, the second spans in the frontend correctly contain the `app.synthetic_request=true` and the loadgenerator contains no attributes (same behaviour as we have for the non-web traffic from the loadgenerator). However, it looks like the first request (fetching) sets the attribute `app.synthetic_request=false`. This is happening due to the behaviour added in [this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/631)

As mentioned @julianocosta89 this was the issue. I have solved it in this last commit https://github.com/open-telemetry/opentelemetry-demo/pull/1345/commits/fd6bc2726da06164f83bb230bfd3927a52fa02e5 by adding a window.env that I can use in the FrontendTracer to not always set the span attribute `app.synthetic_request `to false

**Review by julianocosta89 — APPROVED** [review]
Thanks for the patience @jordibisbal8!
This is great!

**Pull request merged**
