### PR TITLE
Updated packages for several things

### PR DESCRIPTION
**Pull request by CurtisLee-14**
# Changes

Updated several packages including:
GRPC.ASPNETCORE 
GRPC.ASPNETCORE.HealthChecks
GRPC.Net.Client
Microsoft.ASPNetCore.TestHost
Microsoft.Net.Test.SDK

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs][]
* [x] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by austinlparker** [comment]
What's up with the CLA bot here...

**Review by Kielek — COMMENTED** [review]
While upgrading to 1.5.0 it is worth to make some additional cleanup.

I have some local branch for this, but it is waiting for releases mentioned in the second comment.

**Comment by trask** [comment]
just fyi, the CLA issue that was seen in this PR has been fixed by the EasyCLA team

**Comment by wojtekLs** [comment]
> What's up with the CLA bot here...

@austinlparker its only a stupid bot programmed by even more stupid person calling self developer,

**Pull request closed without merging**
