### PR TITLE
ci: ignore coralogix link check

### PR DESCRIPTION
**Pull request by rogercoll**
# Changes

Fix https://github.com/open-telemetry/opentelemetry-demo/issues/1586

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

~~* [ ] `CHANGELOG.md` updated to document new feature additions~~
~~* [ ] Appropriate documentation updates in the [docs][]~~
~~* [ ] Appropriate Helm chart updates in the [helm-charts][]~~

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by rogercoll** [comment]
@austinlparker This PR should unblock other PR's ci

**Review by mviitane — APPROVED** [review]

**Comment by julianocosta89** [comment]
I actually don't like this solution.
I'd rather remove the link from the README.

**Review by chalin — APPROVED** [review]
LGTM

**Comment by chalin** [comment]
> I actually don't like this solution. I'd rather remove the link from the README.

@julianocosta89 - I find that there's value in keeping the link, especially because it is valid; the problem is the link checker, not the link.

Another solution is to _move the **Demos featuring the Astronomy Shop** section of the README_ (that is heavy with external links) **into the OTel website**, probably in the [Demo landing page](https://opentelemetry.io/docs/demo/). Then the OTel.io tooling would handle the link checking.

WDYT?

/cc @open-telemetry/docs-approvers

**Comment by rogercoll** [comment]
> Another solution is to move the Demos featuring the Astronomy Shop section of the README (that is heavy with external links) into the OTel website, probably in the [Demo landing page](https://opentelemetry.io/docs/demo/). Then the OTel.io tooling would handle the link checking.

Sounds good to me too! :+1: Then, just add a reference to the Otel.io url into the demo's readme

**Comment by puckpuck** [comment]
I'm with @julianocosta89 on this. I would prefer we remove the link for Coralogix and get them to fix what is causing issues on their side. Moving this to the Otel demo is just kicking the can down the road, and modifying how our link checker works masks the real problem.

This is a similar situation to one we have encountered in the past when another vendor had issues with their hosting provider.

**Comment by puckpuck** [comment]
Coralogix's hosting provider seems to no longer have an issue with the markdown link checker. I am closing this as it is no longer needed.

**Pull request closed without merging**
