### PR TITLE
[shippingservice] apply OTEL_RESOURCE_ATTRIBUTES

### PR DESCRIPTION
**Pull request by ty-elastic**
Fixes [#593](https://github.com/open-telemetry/opentelemetry-demo/issues/593)

## Changes

* use EnvResourceDetector to load OTEL_RESOURCE_ATTRIBUTES
* merge to existing trace resources

### CODE REVIEW

**Comment by cartersocha** [comment]
Thanks for the bug fix!

Please sign the cla at your earliest convenience so we don’t get blocked merging post reviews.

**Comment by ty-elastic** [comment]
@cartersocha , thx! i fixed the commit ownership.

**Review by julianocosta89 — APPROVED** [review]
LGTM

**Review by julianocosta89 — COMMENTED** [review]
@ty-elastic could you also update https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/services/shippingservice.md#initializing-tracing?

**Review by julianocosta89 — APPROVED** [review]

**Pull request merged**
