### PR TITLE
featureflag: updates the dependency tls_certificate_check to allow bump to OTP-25

### PR DESCRIPTION
**Pull request by tsloughter**
# Changes

Please provide a brief description of the changes here.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Comment by tsloughter** [comment]
I haven't been able to test this yet because even on a clean `main` I can't get the docker compose setup to start up. Will keep trying but opened this in case anyone else can.

**Review by julianocosta89 — APPROVED** [review]
LGTM!

Built it locally and tested the FeatureFlag, all working fine:
image

**Comment by cartersocha** [comment]
Please add a change log entry

**Comment by tsloughter** [comment]
@cartersocha done

**Pull request merged**
