### PR TITLE
chore(kafka): use apache/kafka official image

### PR DESCRIPTION
**Pull request by tranngoclam**
# Changes

- Use official image `apache/kafka` (ref: https://cwiki.apache.org/confluence/display/KAFKA/KIP-975%3A+Docker+Image+for+Apache+Kafka)
- Upgrade otel java instrumentation.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by puckpuck** [comment]
Why do we want to switch from Apache Kafka to Confluent Platform Kafka? This change would also mean the Confluence-specific items in the image would fall under the Confluence Community license, while in the Apache version, everything in the image is under an Apache 2.0 license.

**Comment by austinlparker** [comment]
What's the difference between these two images?

**Comment by tranngoclam** [comment]
> What's the difference between these two images?

@austinlparker it's just more official, under Apache. Additionally:
- size is smaller than the `confluentinc/cp-kafka`: 370MB vs 833MB
- java version is newer (21)

More details in: https://cwiki.apache.org/confluence/display/KAFKA/KIP-975%3A+Docker+Image+for+Apache+Kafka

**Review by mviitane — APPROVED** [review]
Runs fine. Also, KRaft seems to be enabled by default.
`kafka  | Running in KRaft mode...`

**Review by austinlparker — APPROVED** [review]

**Pull request merged**
