### PR TITLE
add metrics to satisfy http server semantic conventions

### PR DESCRIPTION
**Pull request by fatsheep9146**
Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>

related #70 

## Changes

Add more metrics to satisfy [http server metrics semantic coventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-server) 

- http.server.request.size
- http.server.response.size
- http.server.active_requests

http.server.response.size dashboard demo

image

http.server.active_requests dashboard demo

image

### CODE REVIEW

**Review by wph95 — APPROVED** [review]

**Comment by cijothomas** [comment]
Qn - how does the Go front end export this? Is it done via OTLP exporter? Or via Prometheus directly?

**Comment by cijothomas** [comment]
> Qn - how does the Go front end export this? Is it done via OTLP exporter? Or via Prometheus directly?

never mind, I think i got the answer from https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontend/main.go#L108

**Comment by fatsheep9146** [comment]
> > Qn - how does the Go front end export this? Is it done via OTLP exporter? Or via Prometheus directly?
> 
> never mind, I think i got the answer from https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontend/main.go#L108

Yes, via OTLP exporter

**Comment by cartersocha** [comment]
@fatsheep9146, could you update the changelog and then I'll merge

**Comment by cartersocha** [comment]
Trying to get better about that upfront 😄. Do any docs need to be updated? I think we have a centralized metric doc but it's a bit immature

**Comment by puckpuck** [comment]
Would this PR be in conflict with #236 which is replacing frontend with a Next.js based service?

**Comment by fatsheep9146** [comment]
> Would this PR be in conflict with #236 which is replacing frontend with a Next.js based service?

Yes, I think @puckpuck is right, since the whole frontend service is replaces with Next.js implementation. Should I close this pr ? @cartersocha

**Comment by cartersocha** [comment]
Yes let’s wait for the new front end

**Comment by fatsheep9146** [comment]
@cartersocha I think #70 , #49 should also be modified or close to avoid confusion

**Comment by cartersocha** [comment]
Roger that. Thanks for calling them out. Closed for now

**Pull request closed without merging**
