### PR TITLE
🐛 Fixing tests configuration

### PR DESCRIPTION
**Pull request by xoscar**
Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/305.

## Changes

There is an issue with some of the test configurations that weren't caught before merging the prev PR.

### CODE REVIEW

**Comment by xoscar** [comment]
@mviitane Do you mind taking a look?

**Review by mic-max — APPROVED** [review]

**Comment by mviitane** [comment]
> @mviitane Do you mind taking a look?

@xoscar I can still see the same problem when running with your changes. 

Just to be clear, I haven't installed cypress or ava on this machine beforehand, and I think I shouldn't have to, but is that correct?

```
$ docker compose run frontendTests
[+] Running 13/0
 ⠿ Container redis-cart               Running                                                                                                                                                                             0.0s
 ⠿ Container jaeger                   Running                                                                                                                                                                             0.0s
 ⠿ Container otel-col                 Running                                                                                                                                                                             0.0s
 ⠿ Container product-catalog-service  Running                                                                                                                                                                             0.0s
 ⠿ Container recommendation-service   Running                                                                                                                                                                             0.0s
 ⠿ Container cart-service             Running                                                                                                                                                                             0.0s
 ⠿ Container email-service            Running                                                                                                                                                                             0.0s
 ⠿ Container shipping-service         Running                                                                                                                                                                             0.0s
 ⠿ Container ad-service               Running                                                                                                                                                                             0.0s
 ⠿ Container payment-service          Running                                                                                                                                                                             0.0s
 ⠿ Container currency-service         Running                                                                                                                                                                             0.0s
 ⠿ Container checkout-service         Running                                                                                                                                                                             0.0s
 ⠿ Container frontend                 Running                                                                                                                                                                             0.0s
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[228:0817/053441.971654:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[228:0817/053442.010610:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Your configFile is invalid: /cypress/cypress.config.ts

It threw an error when required, check the stack trace below:

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /cypress/cypress.config.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadFile (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter.<anonymous> (/root/.cache/Cypress/10.3.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:32)
$ 
```

```
$ docker compose run integrationTests
[+] Running 12/0
 ⠿ Container redis-cart               Running                                                                                                                                                                             0.0s
 ⠿ Container jaeger                   Running                                                                                                                                                                             0.0s
 ⠿ Container otel-col                 Running                                                                                                                                                                             0.0s
 ⠿ Container cart-service             Running                                                                                                                                                                             0.0s
 ⠿ Container email-service            Running                                                                                                                                                                             0.0s
 ⠿ Container currency-service         Running                                                                                                                                                                             0.0s
 ⠿ Container shipping-service         Running                                                                                                                                                                             0.0s
 ⠿ Container ad-service               Running                                                                                                                                                                             0.0s
 ⠿ Container payment-service          Running                                                                                                                                                                             0.0s
 ⠿ Container product-catalog-service  Running                                                                                                                                                                             0.0s
 ⠿ Container recommendation-service   Running                                                                                                                                                                             0.0s
 ⠿ Container checkout-service         Running                                                                                                                                                                             0.0s

> test@1.0.0 test
> ava

sh: ava: not found
```

**Comment by xoscar** [comment]
@mviitane qq, did you run the build command for both the frontend and the integration tests from the latest commit? I'm not getting those errors 🤔

**Comment by mviitane** [comment]
> @mviitane qq, did you run the build command for both the frontend and the integration tests from the latest commit? I'm not getting those errors 🤔

I ran `docker compose build --no-cache` for the fix-tests branch. It should also build the integrationTests?

**Comment by mviitane** [comment]
@xoscar After re-building with the latest, I got the integrationTests working!  However, the frontendTests still have the same problem.
```
docker compose build frontend --no-cache
docker compose build integrationTests --no-cache
```

**Comment by xoscar** [comment]
Hey @mviitane thanks for the feedback, I figured out what the issue was, do you mind rebuilding the `frontendTests` image and rerunning it again? thanks!

**Comment by mviitane** [comment]
@xoscar Great, I got the tests now running! The frontend tests seem to have 2 tests failing, but I'm not sure if the problem is in the tests or the frontend.

In the original issue, I also proposed to add some simple documentation to test/README.md about how to start the tests. What do you think about that?

**Comment by xoscar** [comment]
@mviitane do you mind taking another look, please rebuild the image and rerun it from the latest commit. I ran it multiple times and got all green
Screen Shot 2022-08-18 at 10 50 47 a m

**Comment by mviitane** [comment]
@xoscar I got now all the frontend tests passing few times, but still at least half of the times some tests were failing.  So some flakiness at least in my env.

Integration tests are passing all the time.

**Review by austinlparker — CHANGES_REQUESTED** [review]
Several things...

1 - Still getting some flakiness in frontend tests.
```
frontend-tests  |
frontend-tests  |   Running:  Checkout.cy.ts                                                                  (1 of 3)
frontend-tests  |
frontend-tests  |
frontend-tests  |   Checkout Flow
frontend-tests  |     1) should create an order with two items
frontend-tests  |
frontend-tests  |
frontend-tests  |   0 passing (7s)
frontend-tests  |   1 failing
frontend-tests  |
frontend-tests  |   1) Checkout Flow
frontend-tests  |        should create an order with two items:
frontend-tests  |      AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy="cart-item-count"]`, but never found it.
frontend-tests  |       at Context.eval (http://frontend:8080/__cypress/tests?p=cypress/e2e/Checkout.cy.ts:111:158)
frontend-tests  |
frontend-tests  |
frontend-tests  |
frontend-tests  |
frontend-tests  |   (Results)
frontend-tests  |
frontend-tests  |   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
frontend-tests  |   │ Tests:        1                                                                                │
frontend-tests  |   │ Passing:      0                                                                                │
frontend-tests  |   │ Failing:      1                                                                                │
frontend-tests  |   │ Pending:      0                                                                                │
frontend-tests  |   │ Skipped:      0                                                                                │
frontend-tests  |   │ Screenshots:  1                                                                                │
frontend-tests  |   │ Video:        true                                                                             │
frontend-tests  |   │ Duration:     6 seconds                                                                        │
frontend-tests  |   │ Spec Ran:     Checkout.cy.ts                                                                   │
frontend-tests  |   └────────────────────────────────────────────────────────────────────────────────────────────────┘
frontend-tests  |
frontend-tests  |
frontend-tests  |   (Screenshots)
frontend-tests  |
frontend-tests  |   -  /app/cypress/screenshots/Checkout.cy.ts/Checkout Flow -- should create an order      (1280x720)
frontend-tests  |      with two items (failed).png
frontend-tests  |
frontend-tests  |
frontend-tests  |   (Video)
frontend-tests  |
frontend-tests  |   -  Started processing:  Compressing to 32 CRF
frontend-tests  |   -  Finished processing: /app/cypress/videos/Checkout.cy.ts.mp4                          (1 second)
```

Didn't see any errors in integration tests, however.

2 - Not clear how these tests should be run, there's no associated `make` target for them or compose target that I could find? I ran them by doing a clean build + `docker compose up`, then running `docker compose up frontendTests` and `docker compose up integrationTests`.

**Comment by xoscar** [comment]
Hey @austinlparker & @mviitane sorry that it took me a while to come back to this PR. With the latest commit, the frontend E2E tests issues should be fixed and I also added an entry to the main Readme file around the test execution and such. Please take a look at let me know what you think. Thanks!

**Comment by julianocosta89** [comment]
Hello @xoscar,

I'm using Ubuntu 22.04 and getting 2 failing tests. Both because there is no item in the cart.

Screenshot from 2022-08-25 22-04-17

Here are the screenshots generated by cypress:
Product Detail Page -- should add item to cart (failed)

Checkout Flow -- should create an order with two items (failed)


When running the `make run-tests`, I'm also getting those errors:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[196:0825/200230.341818:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[196:0825/200230.348329:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
```

Maybe those are responsible for the failure.

**Comment by austinlparker** [comment]
frontend tests passing, integration tests failing, ubuntu 22.04

```
Attaching to integrationTests
integrationTests  |
integrationTests  | > test@1.0.0 test
integrationTests  | > ava
integrationTests  |
integrationTests  |
integrationTests  |   ✔ shipping: order (102ms)
integrationTests  |   ✔ shipping: quote (145ms)
integrationTests  |   ✔ shipping: empty quote (144ms)
integrationTests  |   ✔ ad: get (222ms)
integrationTests  |   ✔ currency: supported (216ms)
integrationTests  |   ✔ currency: convert (216ms)
integrationTests  |   ✔ payment: invalid credit card (192ms)
integrationTests  |   ✔ payment: amex credit card not allowed (192ms)
integrationTests  |   ✔ payment: expired credit card (193ms)
integrationTests  |   ✔ payment: valid credit card (200ms)
integrationTests  |   ✖ product: search Rejected promise returned by test
integrationTests  |   ✔ product: list (232ms)
integrationTests  |   ✖ product: get
integrationTests  |   ✔ recommendation: list products (248ms)
integrationTests  |   ✔ email: confirmation (284ms)
integrationTests  |   ✔ checkout: place order (311ms)
integrationTests  |   ✔ cart: all (348ms)
integrationTests  |   ─
integrationTests  |
integrationTests  |   product: search
integrationTests  |
integrationTests  |   test.js:267
integrationTests  |
integrationTests  |    266:   const res = await productSearch({ query: "hold" });
integrationTests  |    267:   t.is(res.results.length, 2);
integrationTests  |    268:   t.is(res.results[0].name, "Candle Holder");
integrationTests  |
integrationTests  |   Rejected promise returned by test. Reason:
integrationTests  |
integrationTests  |   TypeError {
integrationTests  |     message: 'Cannot read properties of undefined (reading \'length\')',
integrationTests  |   }
integrationTests  |
integrationTests  |   › test.js:267:20
integrationTests  |
integrationTests  |
integrationTests  |
integrationTests  |   product: get
integrationTests  |
integrationTests  |   test.js:258
integrationTests  |
integrationTests  |    257:   const res = await productGet({ id: "OLJCESPC7Z" });
integrationTests  |    258:   t.is(res.name, "Sunglasses");
integrationTests  |    259:   t.truthy(res.description);
integrationTests  |
integrationTests  |   Difference:
integrationTests  |
integrationTests  |   - 'Natiolal Park Foundation Explorascope'
integrationTests  |   + 'Sunglasses'
integrationTests  |
integrationTests  |   › test.js:258:5
integrationTests  |
integrationTests  |   ─
integrationTests  |
integrationTests  |   2 tests failed
integrationTests  | npm notice
integrationTests  | npm notice New minor version of npm available! 8.15.0 -> 8.18.0
integrationTests  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.18.0>
integrationTests  | npm notice Run `npm install -g npm@8.18.0` to update!
integrationTests  | npm notice
integrationTests exited with code 1
```

make run-tests giving an error as well -

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[195:0829/154620.876677:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[195:0829/154620.883062:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
```

**Comment by xoscar** [comment]
Ok everyone, thank you for your patience. I think I finally fixed the tests. The warning at the beginning shouldn't be a problem, tests should pass either way.

For the integration tests I fixed the ones related to the catalog changes. But there is one outstanding issue regarding the C++ service not returning the right amount of supported currencies.

CC: @austinlparker @mviitane @julianocosta89

**Comment by julianocosta89** [comment]
`docker compose run frontendTests` Failing with the following:

```
#0 46.15 npm WARN deprecated @types/bson@4.2.0: This is a stub types definition. bson provides its own type definitions, so you do not need this installed.
#0 54.21 npm ERR! code ERR_SOCKET_TIMEOUT
#0 54.21 npm ERR! network Socket timeout
#0 54.21 npm ERR! network This is a problem related to network connectivity.
#0 54.21 npm ERR! network In most cases you are behind a proxy or have bad network settings.
#0 54.21 npm ERR! network
#0 54.21 npm ERR! network If you are behind a proxy, please make sure that the
#0 54.21 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
#0 54.22
#0 54.22 npm ERR! A complete log of this run can be found in:
#0 54.22 npm ERR!     /root/.npm/_logs/2022-08-31T06_01_29_133Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm ci]: exit code: 1
```

I though it was something going on with my machine or docker, but the `integrationTests` are working:

```
> test@1.0.0 test
> ava


  ✔ email: confirmation
  ✔ payment: invalid credit card
  ✔ payment: amex credit card not allowed
  ✔ payment: expired credit card
  ✔ payment: valid credit card
  ✔ product: list
  ✔ product: search
  ✔ product: get
  ✔ recommendation: list products
  ✔ shipping: order
  ✔ shipping: quote
  ✔ shipping: empty quote
  ✔ currency: supported
  ✔ currency: convert
  ✔ checkout: place order
  ✔ cart: all
  ✔ ad: get (417ms)
  ─

  17 tests passed
```

Lets just wait to see if someone else is having the same issue with the `frontendTests`

**Comment by mviitane** [comment]
With the latest version, I'm not able to get the tests started. For some reason I get
`Error response from daemon: network 280c24c522b9ab9573d736848ecd13aaf79198f424f3d1e385a6a61676a72084 not found`

The demo app is running fine though.

@xoscar, you could also merge from main to get #350 included.

**Comment by xoscar** [comment]
@mviitane done 😄

**Review by mic-max — APPROVED** [review]

**Comment by julianocosta89** [comment]
hey @xoscar is that expected?
https://github.com/open-telemetry/opentelemetry-demo/pull/306#issuecomment-1232501206

**Comment by xoscar** [comment]
@cartersocha with the latest version that shouldn't happen anymore

**Comment by julianocosta89** [comment]
`docker compose run frontendTests`

```
     Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  Checkout.cy.ts                           00:09        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  Home.cy.ts                               00:01        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  ProductDetail.cy.ts                      00:05        2        2        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:15        5        5        -        -        -
```


`docker compose run integrationTests`
```
> test@1.0.0 test
> ava


  ✔ currency: supported
  ✔ currency: convert
  ✔ email: confirmation
  ✔ payment: invalid credit card
  ✔ payment: amex credit card not allowed
  ✔ payment: expired credit card
  ✔ payment: valid credit card
  ✔ product: list
  ✔ product: search
  ✔ recommendation: list products
  ✔ shipping: quote
  ✔ shipping: empty quote
  ✔ shipping: order
  ✔ ad: get (102ms)
  ✔ checkout: place order
  ✔ cart: all (113ms)
  ✔ product: get (6.9s)
  ─

  17 tests passed
```

**Review by julianocosta89 — DISMISSED** [review]

**Comment by julianocosta89** [comment]
@xoscar just to be sure, I've ran again the tests, and I got an error with the checkout within the frontendTests.
I looks like the tests are flaky 😢 
Checkout Flow -- should create an order with two items (failed)

**Comment by austinlparker** [comment]
> @austinlparker @cartersocha can we prioritize merging this PR? I think even if the tests might be flaky these changes are required to have them running as part of docker compose. We can fix the flaky test in a follow-up PR.

If we can't fix the flaky tests in this PR, why would another PR help? Why would we want the tests to run as part of compose if they aren't reliable?

**Comment by cartersocha** [comment]
@xoscar we decided in the sig call to move forward with only the non flaky tests for now. Post v1 will be updated or re-examined.

Please cut the scope down a bit to the reliable tests

**Comment by xoscar** [comment]
@cartersocha sorry for the late response, I took one week off 😅 I just updated the PR skipping the flaky tests. Let me know what you think. @austinlparker

**Comment by mviitane** [comment]
**The frontend tests** seem stable now
```
      Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  Checkout.cy.ts                            20ms        1        -        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  Home.cy.ts                               00:03        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  ProductDetail.cy.ts                       20ms        2        -        -        2        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:03        5        2        -        3        -  

```

**The integration tests** run successfully when first starting the app with
`docker compose up`

And then using another terminal
`docker compose run integrationTests`

**Review by mviitane — APPROVED** [review]

**Comment by cartersocha** [comment]
@julianocosta89, @austinlparker could we get another pass of reviews here?

**Review by julianocosta89 — CHANGES_REQUESTED** [review]
@xoscar with the changes on the shipping service, which now gets the quote from the quoteservice, in order to get the tests to succeed we need to do what @mviitane mentioned.
1st `docker compose up`

And then using another terminal
`docker compose run integrationTests`

We need to either update the README or update the the test to start the `quoteservice`together with the test.

**Comment by xoscar** [comment]
@julianocosta89 @austinlparker @cartersocha done 😄  I added the quote service as a dependency of the `integrationTests`

**Review by julianocosta89 — APPROVED** [review]

**Comment by julianocosta89** [comment]
@austinlparker do you mind trying it as well?

**Comment by julianocosta89** [comment]
@cartersocha I think we are good to go with this one

**Comment by austinlparker** [comment]
Needs to be rebased! @xoscar

**Comment by reyang** [comment]
> Needs to be rebased! @xoscar

Curious - are folks trying to achieve "zero open PRs" today? 😆

**Comment by xoscar** [comment]
@reyang done :)

**Comment by reyang** [comment]
> @reyang done :)

Wow!! I guess we might see for the 1st time that an OpenTelemetry repository reaching zero opening PR 🍾🍾🍾🥇🥇🥇

**Comment by cartersocha** [comment]
@xoscar one more time please? Im waiting on the merge button 😉

**Comment by cartersocha** [comment]
@reyang I can close my language update PR if needed lolol

**Comment by cartersocha** [comment]
For the day

**Comment by xoscar** [comment]
@cartersocha I think it should be visible now

**Pull request merged**
