### PR TITLE
build protobuf in dockerfile for all services

### PR DESCRIPTION
**Pull request by fsolleza**
# Changes

Problem: Small changes to protobuf require extensive tooling to generate protobuf using `make generate-protobuf`. `ide-gen-proto.sh` shows how some service's protobuf might be generated.

Four services' generated protobuf code were moved to container build time. This doesn't replace `make generate-protobuf` which is still useful when understanding the protobuf code outside of build time. It makes `make start` and friends friendlier to small changes to `pb/demo.proto`.

The four services affected are:

- accountingservice
- checkoutservice
- productcatalogservice
- currencyservice

This was discussed here: https://github.com/open-telemetry/opentelemetry-demo/issues/1374

* This is a resubmit of another PR where the email address (and resulting CLA) was messed up for some reason.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by fsolleza** [comment]
I'm not exactly sure why currencyservice is failing the build?

Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref cewwk3g7np5pflqnggalica0g::oepmw7nh6irdnl07gnw8ofc9c: failed to walk /tmp/buildkit-mount1551154311/src: lstat /tmp/buildkit-mount1551154311/src: no such file or directory

Happy to fix if pointed the right way.

**Comment by austinlparker** [comment]
Interesting. Looks like it can't find the source directory in builder somehow, but it works locally. Gonna poke at it a bit.

**Comment by austinlparker** [comment]
Oh, duh. Ok, the problem is the changes you made to the context path in the docker compose file.

**Comment by austinlparker** [comment]
I think it should work now. You changed the build context in the compose file, but not in the GitHub workflow, so the docker context was being set to `./src/currencyservice` rather than `./`

**Review by austinlparker — APPROVED** [review]

**Pull request merged**
