### PR TITLE
[chore] Bump .NET dependencies

### PR DESCRIPTION
**Pull request by Kielek**
# Changes

Update .NET dependencies related to:
OTel .NET release 1.4.0
Rename package `OpenTelemetry.Extensions.Docker` to `OpenTelemetry.ResourceDetectors.Container`.
Bump docker base images to 6.0.16/6.0.408 - to include security fixes from latest .NET 6 release.
Opportunistic update for non-otel packages

Cannot bump `Grpc.AspNetCore` to 2.52.0 due to https://github.com/grpc/grpc-dotnet/issues/2079. It should be fixed with next release.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* ~~[ ] `CHANGELOG.md` updated to document new feature additions~~ only updated packages, not changelog entry needed
* ~~[ ] Appropriate documentation updates in the [docs][]~~

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Comment by Kielek** [comment]
Tested with locally build docker image, no issues/warnings
image

**Comment by cartersocha** [comment]
FYI @puckpuck @austinlparker @julianocosta89 1.4 or 1.5? Seems minor but I know we're close to the release

**Comment by cartersocha** [comment]
@Kielek thanks for the updates. We'd still love to add the dotnet auto instrumentation to a service if y'all have any interest!

**Comment by austinlparker** [comment]
I think this can go in for 1.4

**Comment by puckpuck** [comment]
Yeah we can do this 1.4

**Review by puckpuck — APPROVED** [review]

**Review by fatsheep9146 — APPROVED** [review]

**Pull request merged**
