### PR TITLE
Add resource detection to checkout service

### PR DESCRIPTION
**Pull request by svrnm**
# Changes

Similar to #648 & #651 this adds more resources being detected to the checkout service. 

Screenshot 2022-12-27 at 23 35 07

## Merge Requirements

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs](../docs/) folder

### CODE REVIEW

**Review by fatsheep9146 — APPROVED** [review]

**Comment by fatsheep9146** [comment]
Thanks for addition, looks good to me.
BTW I wonder what about the metricsprovider, will you add in the future?

**Comment by svrnm** [comment]
> Thanks for addition, looks good to me. BTW I wonder what about the metricsprovider, will you add in the future?

Haven't thought about it to be honest, I fixed that now :)

**Review by julianocosta89 — APPROVED** [review]
LGTM!

**Comment by julianocosta89** [comment]
@svrnm just out of curiosity, from where the `container.id` comes from?
I've tested the PR and only got `host.name`, which has the initial part of the container id, and not the whole ID as you have in the screenshot.
BTW: Tested it out just with docker.

**Comment by mviitane** [comment]
Same for me.
`container.id` is not visible, `host.name` is visible
When looking at other services like paymentservice, I can see  `container.id` just fine, so shouldn't be a problem in the docker environment.

**Comment by svrnm** [comment]
Same here, Limitation rg cgroup v2. PR is in the making as well:

https://github.com/open-telemetry/opentelemetry-go/pull/3508

**Comment by cartersocha** [comment]
I think the changelog has a conflict from the cart service pr but ready to merge when resolved

**Review by cartersocha — APPROVED** [review]

**Comment by fatsheep9146** [comment]
@cartersocha I fix the conflicts. I think the pr is ready to merged.

**Comment by cartersocha** [comment]
https://giphy.com/gifs/luffy-zKBcZUw49Sxtm

@fatsheep9146

**Pull request merged**
