### PR TITLE
Fix python loadgenerator memory leak

### PR DESCRIPTION
**Pull request by cartersocha**
My good friend ChatGPT and I tried a couple different solutions to eliminate the memory leak here. 

The most effective method seemed to be switching to the locustio image as our base image from a generic python option. 

I ran both versions locally for ~40 mins. The locustio image stabilized around 67 MB usage. The regular python image continued to add memory usage overtime and was around 86 MB usage when I stopped it. 
Screenshot 2023-03-30 at 10 41 26 AM
Screenshot 2023-03-30 at 11 20 10 AM

### CODE REVIEW

**Comment by cartersocha** [comment]
towards: https://github.com/open-telemetry/opentelemetry-demo/issues/771

**Comment by puckpuck** [comment]
oooh... this looks super interesting.  Will give it a try on a long running tests

Wonder if we can do the same for the emailservice now 😛

**Comment by puckpuck** [comment]
I have this running now. Loadgenerator was OOMing every 55-ish hours before.

**Review by julianocosta89 — APPROVED** [review]
Image size grew 100MB, but for the benefit that this is bringing I don't have anything against it.
Nice finding @cartersocha!

**Comment by cartersocha** [comment]
@puckpuck im guessing no news is good news on restarts! Are we good to merge once I resolve the conflicts or have any issues popped up?

**Comment by puckpuck** [comment]
I'll confirm tonite one way or the other.

**Review by fatsheep9146 — APPROVED** [review]

**Comment by puckpuck** [comment]
I still see a memory leak, at about the same rate as before :(

**Pull request closed without merging**
