### PR TITLE
[collector] use spanmetrics connector instead of spanmetrics processor

### PR DESCRIPTION
**Pull request by fatsheep9146**
# Changes

I would suggest updating opentelemetry-demo to use the [spanmetrics connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector) instead of the [spanmetrics processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanmetricsprocessor), as the latter has been deprecated. 

By doing this we can also let user to take advantage of the new advanced functionality `connector`.

I also modify the spanmetric dashboard to be compatible with breaking changes from the spanmetrics connector, which are listed in (here)[Compatibility with important changes to the Spanmetrics connector
]

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs][]

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Comment by julianocosta89** [comment]
Assuming this is outdated: https://github.com/open-telemetry/opentelemetry-collector/blob/main/connector/README.md#status
It looks good to me.

If the `connectors` are still in `alpha`, than, I'd rather wait to it to get to at least to `beta`. Otherwise, maintaining all the possible changes will be a pain.

@austinlparker, you have mentioned that the README was probably outdated, right?

**Comment by julianocosta89** [comment]
@fatsheep9146 could you also add a changelog?

**Comment by fatsheep9146** [comment]
> @fatsheep9146 could you also add a changelog?

Done

**Comment by fatsheep9146** [comment]
> If the `connectors` are still in `alpha`, than, I'd rather wait to it to get to at least to `beta`. Otherwise, maintaining all the possible changes will be a pain.

I think this also makes sense. But I just want to experience with this useful feature, since the `connector` and `spanmetrics connector` are both marvelous features introduced into collector. And I think their design is really fully reviewed. 
If you think we should not use them until they enter into beta, I'm also ok with that. :)

@julianocosta89

**Comment by julianocosta89** [comment]
I had some personal issues with beta releases b4 😅 .
But that's a me thing.

I'm good to go either way, just want to hear from everyone first.

**Comment by austinlparker** [comment]
Given the cadence of collector releases and how quickly things move thru maturity phases, I'd argue that we should pick up connectors now in order to get useful feedback for collector devs?

**Review by austinlparker — APPROVED** [review]

**Pull request merged**
