### PR TITLE
spanmetrics dashboard premiere

### PR DESCRIPTION
**Pull request by devrimdemiroz**
# Changes
Sample spanmetrics dashboard showing service and operational level throughputs and latencies.

Light-spanmetrics_dashboard2

DarkBlues-spanmetrics_dashboard

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Review by puckpuck — APPROVED** [review]
This is fantastic! 
Thank you for this.

**Comment by fatsheep9146** [comment]
awesome!

**Review by fatsheep9146 — APPROVED** [review]

**Review by julianocosta89 — APPROVED** [review]
I loved it! 🤩

**Review by mviitane — APPROVED** [review]
Looks really good!

**Comment by devrimdemiroz** [comment]
Thanks for accepting it. With my pleasure! 🥳  

Very soon, we will need to change the spanmetrics naming, namespace, and metric structure ... a breaking change is incoming.

**Pull request merged**
