### PR TITLE
[java-services] Update java, gradle and OTel agent versions

### PR DESCRIPTION
**Pull request by julianocosta89**
# Changes

This PR updates the java version on AdService to latest LTS Java (21).
Unfortunately, there is jvm target `21` for Kotlin yet, so for FraudDetection I've just update gradle to version `8.4`.
Also bumped the Java OTel agent in the 3 services its being used.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by cedricziel — APPROVED** [review]
lgtm

**Comment by julianocosta89** [comment]
> It's a great improvement to use Log4j2 so logs can be captured via auto-instrumentation and send through OTLP.
> 
> Did you consider enabling `otel.logs.exporter=otlp` / `OTEL_LOGS_EXPORTER=otlp` the same way it is done on the Java adservice (done through an env variable) and the Python recommendationservice (done through code):
> 
> * https://github.com/open-telemetry/opentelemetry-demo/blob/1.5.0/kubernetes/opentelemetry-demo.yaml#L7067
> * https://github.com/open-telemetry/opentelemetry-demo/blob/1.5.0/src/recommendationservice/recommendation_server.py#L143C5-L143C17

AFAIK `otlp` is the default logs exporter, isn't it?

In this PR I'm also adding log4j2 to the Kotlin service, so we also have OTLP traces for FraudDetection.
AdService has it already.

Am I missing something @cyrille-leclerc ?

**Comment by cedricziel** [comment]
The java-otel README for the autoconfigurer states:

```
| otel.logs.exporter    | OTEL_LOGS_EXPORTER    | List of exporters to be used for logging, separated by commas. Default is `otlp`. `none` means no autoconfigured exporter. |
```

https://github.com/open-telemetry/opentelemetry-java/blob/57d83344178f578eb5d2f043b0ffc5c42b6719a5/sdk-extensions/autoconfigure/README.md?plain=1#L79

To my understanding, we should be good with this change

**Comment by cyrille-leclerc** [comment]
You are right, nothing to do in the demo. Logs auto instrumentation got enabled by default in 1.27.0 but the release notes of the auto-instrumentation agent didn't mention it, it just appeared on the release notes of he auto-configure-sdk:

* https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.27.0
* https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.27.0

**Review by cedricziel — APPROVED** [review]

**Review by puckpuck — APPROVED** [review]

**Comment by cyrille-leclerc** [comment]
Sorry @julianocosta89 and @cedricziel, OTel Logs are disabled by default on the OTel Java Auto Instrumentation agent. Logs will be enabled by default in 2.0. Shall we enable it on the OTel Demo?

See 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/97d87f3f3b2bc61aa396d71a98387a1e857618af/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/OpenTelemetryInstaller.java#L31-34

And

* https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9008

**Comment by julianocosta89** [comment]
@cyrille-leclerc the logs are already enabled for AdService, and this PR adds it to the FraudDetectionService.

I'm not sure what you would like to add.

Please feel free to send a PR with your suggestions.

**Pull request merged**
