### PR TITLE
chore: Update PHP Dependencies

### PR DESCRIPTION
**Pull request by calmius**
# Changes

Updated php dependencies
Issue Number: close [#994 ](https://github.com/open-telemetry/opentelemetry-demo/issues/994)

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [X] `CHANGELOG.md` updated to document new feature additions

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

### CODE REVIEW

**Comment by julianocosta89** [comment]
@calmius could you sign the CLA?

**Comment by calmius** [comment]
> @calmius could you sign the CLA?

**Comment by calmius** [comment]
> LGTM. Fix: #994 

Oh, sorry for wrong order in Changelog, didn't notice numbering

**Comment by julianocosta89** [comment]
> > LGTM. Fix: #994 
> 
> Oh, sorry for wrong order in Changelog, didn't notice numbering 

No worries!
It was a 1 sec job 😊

**Pull request merged**
