### PR TITLE
Delete server_test.go

### PR DESCRIPTION
**Pull request by mic-max**
No longer needed. Replaced this testing within the file `/test/test.js`

### CODE REVIEW

**Review by puckpuck — APPROVED** [review]

**Review by mviitane — APPROVED** [review]

**Comment by puckpuck** [comment]
@mic-max can you update the branch so we can merge this?

**Comment by mic-max** [comment]
> @mic-max can you update the branch so we can merge this?

I can't. I accidentally made this change from GitHub website so it defaults to being made on the repository and not my fork. @cartersocha could you update/merge please?

**Comment by cartersocha** [comment]
I get cla errors trying to update it. @mic-max could you just open a new pr?

**Comment by cartersocha** [comment]
Closing in favor of: https://github.com/open-telemetry/opentelemetry-demo/pull/297 to avoid merge problem

**Pull request closed without merging**
