### PR TITLE
Add trace based testing examples

### PR DESCRIPTION
**Pull request by danielbdias**
# Changes

On this PR, we are adding some examples of [Trace-based test cases](https://docs.tracetest.io/concepts/what-is-trace-based-testing) that can be run against the demo and can be used to validate the traces emitted for each service, discussed on https://github.com/open-telemetry/opentelemetry-demo/issues/873.

To do that, we added the [tracetest](https://github.com/kubeshop/tracetest) server on the `docker-compose.yaml` to run tests against the infrastructure and added a set tests for each service on `./test/tracetesting`.

You can run these tests manually by running the following command:  `make run-tracetesting`

## Merge Requirements

For new features contributions, please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by austinlparker** [comment]
Please make sure you sign the CLA

**Comment by danielbdias** [comment]
Hi everyone! I was able to sign the CLA and fix some of the issues reported by the Github Actions.

In this first part of the PR, I've added four trace-based tests: 
- one simulating a user doing a checkout process;
- three porting AVA tests to tracetest, checking both the outcome of the API call and some properties of the traces emitted  by it.

Does it make sense to you? If yes, the next two steps that I can do on this PR are:
1. Port the other AVA tests to tracetest, asserting the API outcome and the properties of the traces emitted by the APIs;
2. Build a Github Action that will have the following idea:
```sh
# install tracetest on this container
curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash

# run services in docker-compose
```

**Comment by danielbdias** [comment]
Hi everyone! I updated this PR based on our latest interaction and fixed tracetest version to a RC version (that will be released this week) to solve two things:

1. intermittency that was causing tracetest to not print the test values to the cart test;
2. an update to refer to the protobuf file in the test files instead of embedding it, which made this PR shorten from 7000 lines to 1000.

Feel free to ask anything and to make suggestions or comments about this PR!

**Comment by austinlparker** [comment]
- This will need to be updated to work with #872 
- Align trace tests with load generator routes being exercised

**Comment by austinlparker** [comment]
Waiting on #872

**Comment by danielbdias** [comment]
Hi folks! 

I updated this PR to comply with the startup division that will happen on #872 . 

The idea of this PR is to divide and have trace-based tests per service that will be triggered on `[run.bash](https://github.com/open-telemetry/opentelemetry-demo/pull/877/files#diff-204cfe2d5af2a0b9933d5b24f206a36ba73aa3b1c694877d794ed6013dd91d69)`.

Today the test runner called all services, but as soon as we have #872 merged, I'll update it to call the available services.

Also, I've updated the tests for the `frontend-service` to have the same URL calls as the `load-generator`.

**Comment by danielbdias** [comment]
I saw that https://github.com/open-telemetry/opentelemetry-demo/pull/872 was merged now. I will work on this PR to support it.

**Pull request merged**
