### PR TITLE
[chore] - update kubernetes manifests to 1.7 release

### PR DESCRIPTION
**Pull request by puckpuck**
Updates k8s manifest to 1.7 release

`make generate-kubernetes-manifests`

### CODE REVIEW

**Review by julianocosta89 — APPROVED** [review]
LGTM!
Should we also create the namespace `otel-demo` in this file?

**Comment by puckpuck** [comment]
That's a good idea. I will figure out the right way to do this with the generator script.

**Comment by mviitane** [comment]
A bit related comment: 
Our helm and kubectl install commands in the docs are not aligned with what comes to the namespace. Helm install doesn't include namespace at all, even if it should?, and leads to installing to the default namespace.

**Comment by puckpuck** [comment]
I added a create namespace manifest the hard way to the generated output. Unfortunately, the `helm template ...` command will not emit this for us.

@julianocosta89 can you take another look?

**Review by fatsheep9146 — APPROVED** [review]

**Review by julianocosta89 — APPROVED** [review]

**Pull request merged**
