### PR TITLE
Add healthcheck to featureflagservice

### PR DESCRIPTION
**Pull request by cedricziel**
# Changes

In order to assess the health of this central service, compose should perform a check on the service.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

### CODE REVIEW

**Comment by mic-max** [comment]
I believe we have decided on monitoring the health using Kubernetes and on not supporting doing through docker like your proposal.

**Comment by cedricziel** [comment]
Why is that? If a certain service fails in the docker compose scenario, how do you know (other than fallout)?

Does that mean the primary intention of this project is to be run on k8s? Then we should probably remove the docker compose file.

**Review by julianocosta89 — APPROVED** [review]
I personally like the addition.
There is a discussion going on that may change this though.
@cedricziel please feel free to add your insights in here: #635

**Comment by cedricziel** [comment]
@julianocosta89 thanks for raising awareness!

**Review by fatsheep9146 — APPROVED** [review]

**Comment by julianocosta89** [comment]
@puckpuck should we do something regarding helm in this one?
Otherwise, I think we are good to merge this one

**Review by puckpuck — APPROVED** [review]

**Pull request merged**
