### PR TITLE
Add OTel logo to README

### LINKED ISSUE #742: README: add OTel logo back
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry-demo/issues/730#issuecomment-1419299765_

>> We should keep the otel image for the main readme but maybe just create another folder. Otherwise lgtm
>
> @cartersocha - would it be ok to address this separately? (We have at least two options, the details of which I'd rather discuss in the context of a followup PR or issue.)

### PR DESCRIPTION
**Pull request by chalin**
- Closes #742
- Adds OTel logo, fetched from [opentelemetry.io], back to the title (level 1 heading) of the README.md file
- No `CHANGELOG.md` entry required, I suppose :).

[opentelemetry.io]: https://opentelemetry.io/docs/demo/

/cc @cartersocha

### CODE REVIEW

**Review by cartersocha — APPROVED** [review]

**Comment by cartersocha** [comment]
Looks like I'm able to merge @chalin so we're good to go. I'll wait for another review first but thanks again for all the migration work you've done. Spotlighting the demo and docs on the website has made a significant difference in repo usage and I know it's been an involved process

**Comment by cartersocha** [comment]
I think our weekly repo visitor count has doubled. 

Thanks to @svrnm and @cartermp too! 🎆

**Comment by chalin** [comment]
> I think our weekly repo visitor count has doubled.

Amazing! I really appreciate the feedback and stats. I'm glad that there has been such a positive impact! ✨

**Review by fatsheep9146 — APPROVED** [review]

**Comment by cartersocha** [comment]
github Small
Some more fun data

**Pull request merged**
