### PR TITLE
Added Teletrace forked opentelemetry demo repo to Readme

### PR DESCRIPTION
**Pull request by haimrait**
# Changes

Added a link to Teletrace open telemetry demo repo from readme file.
[Teletrace](https://docs.teletrace.io/) is an open-source troubleshooting tool based on traces, designed for cloud-native distributed applications.
[Teletrace repo](https://github.com/teletrace/teletrace)

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Review by julianocosta89 — CHANGES_REQUESTED** [review]
Hello @haimrait 👋🏽 

We follow alphabetical order in this table. Could you move Teletrace to after TelemetryHub?

**Comment by haimrait** [comment]
@julianocosta89 Hey sure, its done

**Comment by julianocosta89** [comment]
hey @haimrait sorry about that, but the table is a bit weird 😅 

It is like that:

A   |  D
B   |  E
C   |  F

**Comment by haimrait** [comment]
Screenshot 2023-04-13 at 14 34 57 Done.

**Review by julianocosta89 — APPROVED** [review]
Yep!
Thx @haimrait!

**Review by fatsheep9146 — APPROVED** [review]

**Pull request merged**
