### PR TITLE
Allow Grafana to start without an Internet connection

### PR DESCRIPTION
**Pull request by flands**
# Changes

Addresses #1627

## Merge Requirements

None

### CODE REVIEW

**Comment by puckpuck** [comment]
With these changes, and disconnected to the Internet, I still get the `no healthy upstream` error when going to http://localhost/grafana/. The grafana logs show this message: 

```
Error: ✗ Get "https://grafana.com/api/plugins/grafana-opensearch-datasource/versions": dial tcp: lookup grafana.com on 127.0.0.11:53: no such host
```

**Comment by puckpuck** [comment]
I also ask if this is functionality that we should target to support since several of the images needed to run the demo, including Grafana itself, are not even built locally.

**Review by cedricziel — APPROVED** [review]

**Review by julianocosta89 — COMMENTED** [review]
I'm not sure why, but I still get an error when offline:

```
Error: ✗ Get "https://grafana.com/api/plugins/grafana-opensearch-datasource/versions": dial tcp: lookup grafana.com on 127.0.0.11:53: no such host
```

**Comment by puckpuck** [comment]
I believe the issue here is that the OpenSearch plugin (and perhaps others) is not part of Grafana's core distribution and image. When Grafana starts up, it will download the latest version of the plugin and enable it.

**Comment by flands** [comment]
It appears the proposed changes will not work. If you start with an Internet connection, you will see the following Grafana logs:

```
✔ Downloaded and extracted grafana-opensearch-datasource v2.16.1 zip successfully to /var/lib/grafana/plugins/grafana-opensearch-datasource
logger=plugins.registration t=2024-06-30T12:45:07.602529512Z level=info msg="Plugin registered" pluginId=grafana-opensearch-datasource
logger=provisioning.datasources t=2024-06-30T12:45:07.681012346Z level=info msg="inserting datasource from configuration" name=OpenSearch uid=P9744FCCEAAFBD98F
```

It seems like one approach to solve this would be to bundle the plugin with the demo releases and mount it on start. Alternatively, state would need to be persisted, at least for Grafana, across restarts. Closing this.

**Comment by GeorgeGkinis** [comment]
I changed the opensearch configuration to use the bundled elasticsearch datasource in `src/grafana/provisioning/datasources/opensearch.yaml`:

```
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: OpenSearch
    type: elasticsearch
    url: http://opensearch:9200/
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      database: otel
      flavor: opensearch
      logLevelField: severity
      logMessageField: body
      pplEnabled: true
      timeField: observedTimestamp
      version: 2.17.1

```
I also had to comment this out in `docker-compose.yaml`:
```
    #environment:
      #- "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
```

grafana starts up and seems to work so far.
I see data in the dashboards.

**Pull request closed without merging**
