### PR TITLE
[loadgenerator] Bump deps and update container base image

### PR DESCRIPTION
**Pull request by julianocosta89**
# Changes

For some unknown reason the loadgenerator container image had a size of 1.02GB.
When updating the `Dockerfile`, I've also updated the dependencies and tidied up a bit the `locustfile.py`.

Now the image has a size of 135MB.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs](../docs/) folder

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

### CODE REVIEW

**Comment by fatsheep9146** [comment]
I think changelog is needed.

**Review by mviitane — CHANGES_REQUESTED** [review]
Install of the requirements is not working (with Docker Desktop, Mac M1):

```
$ docker system prune -a
$ docker compose build loadgenerator 
 [+] Building 16.2s (10/13)                                                                                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 987B                                                                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                       0.0s
 => => transferring context: 1.04kB                                                                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/python:3.11-alpine3.17                                                                                                                                                                               1.7s
 => importing cache manifest from ghcr.io/open-telemetry/demo:v1.2.1-loadgenerator                                                                                                                                                                      1.6s
 => [internal] load build context                                                                                                                                                                                                                       0.1s
 => => transferring context: 9.44kB                                                                                                                                                                                                                     0.0s
 => [base 1/1] FROM docker.io/library/python:3.11-alpine3.17@sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a                                                                                                                    2.4s
 => => resolve docker.io/library/python:3.11-alpine3.17@sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a                                                                                                                         0.0s
 => => sha256:261da4162673b93e5c0e7700a3718d40bcc086dbf24b1ec9b54bca0b82300626 3.26MB / 3.26MB                                                                                                                                                          0.4s
 => => sha256:e1c6f98fd0547fcc6cd773da260cc8d980e3beeceffd4c0805fb00942a7175e3 624.83kB / 624.83kB                                                                                                                                                      0.5s
 => => sha256:45a28ad63eb058b6b4c2b3a90a0160e7bd2eb2a4c481b313b2e3226af2b58c35 12.80MB / 12.80MB                                                                                                                                                        1.6s
 => => sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a 1.65kB / 1.65kB                                                                                                                                                          0.0s
 => => sha256:5693bfba00d784b3bb48b1f485233a2ac845946cde2a65427e316882b3e2f564 1.37kB / 1.37kB                                                                                                                                                          0.0s
 => => sha256:bbd3f7c28acebf719a48db90839073e2d32da8a1d44d9686613ca58ec56942f9 7.05kB / 7.05kB                                                                                                                                                          0.0s
 => => extracting sha256:261da4162673b93e5c0e7700a3718d40bcc086dbf24b1ec9b54bca0b82300626                                                                                                                                                               0.2s
 => => sha256:fe2bfecb80211f62678e1546cdef5581c5a13c349b5f94fa182d6003b7e2e548 230B / 230B                                                                                                                                                              0.5s
 => => sha256:b1fe52bb1731b2f5a7a7c38544faa2cbd654ecebbf287757c5e12d0d3c0c35a9 3.06MB / 3.06MB                                                                                                                                                          0.9s
 => => extracting sha256:e1c6f98fd0547fcc6cd773da260cc8d980e3beeceffd4c0805fb00942a7175e3                                                                                                                                                               0.3s
 => => extracting sha256:45a28ad63eb058b6b4c2b3a90a0160e7bd2eb2a4c481b313b2e3226af2b58c35                                                                                                                                                               0.4s
 => => extracting sha256:fe2bfecb80211f62678e1546cdef5581c5a13c349b5f94fa182d6003b7e2e548                                                                                                                                                               0.0s
 => => extracting sha256:b1fe52bb1731b2f5a7a7c38544faa2cbd654ecebbf287757c5e12d0d3c0c35a9                                                                                                                                                               0.2s
 => [builder 1/3] RUN apk add gcc linux-headers musl-dev                                                                                                                                                                                                3.2s
 => [stage-2 1/4] WORKDIR /usr/src/app/                                                                                                                                                                                                                 0.1s
 => [builder 2/3] COPY ./src/loadgenerator/requirements.txt .                                                                                                                                                                                           0.0s 
 => ERROR [builder 3/3] RUN pip install --prefix="/reqs" -r requirements.txt
...

#0 6.923       Failed to build cffi
#0 6.923       Installing collected packages: setuptools, pycparser, greenlet, Cython, cffi
#0 6.923         Running setup.py install for cffi: started
#0 6.923         Running setup.py install for cffi: finished with status 'error'
#0 6.923         error: subprocess-exited-with-error
#0 6.923       
#0 6.923         × Running setup.py install for cffi did not run successfully.
#0 6.923         │ exit code: 1
```

**Comment by julianocosta89** [comment]
@mviitane would you be able to try it again?

**Comment by mviitane** [comment]
> @mviitane would you be able to try it again?

I now get further, but it still fails:

```
#0 27.56 Building wheels for collected packages: flask-basicauth, gevent, grpcio, markupsafe, msgpack, psutil, roundrobin, wrapt, zope-interface
#0 27.56   Building wheel for flask-basicauth (setup.py): started
#0 27.73   Building wheel for flask-basicauth (setup.py): finished with status 'done'
#0 27.73   Created wheel for flask-basicauth: filename=Flask_BasicAuth-0.2.0-py3-none-any.whl size=4241 sha256=1ac0f649a72d37c37be9509708d3c5562a5e3af06b0e4e0e1aa47e8169c25f08
#0 27.73   Stored in directory: /root/.cache/pip/wheels/b7/ac/af/20577bcc2e68ce45b0b40376df225e259ee98867c4afd79c1d
#0 27.73   Building wheel for gevent (pyproject.toml): started
#0 31.13   Building wheel for gevent (pyproject.toml): finished with status 'error'
#0 31.14   error: subprocess-exited-with-error
```

**Comment by julianocosta89** [comment]
@mviitane how about now?

**Comment by julianocosta89** [comment]
Thank you very much @mviitane, that was an interesting one.
Lets wait for some others to take a look, and if we get this merged I'll follow the same approach with the `recommendationservice` that has also a big image size.

**Review by fatsheep9146 — APPROVED** [review]

**Comment by cartersocha** [comment]
Let's discuss this on Monday! That image size reduction is huge

**Pull request merged**
