### PR TITLE
Currency Service (CPP) with Alpine Packages

### PR DESCRIPTION
**Pull request by svrnm**
# Changes

In this PR the currency service dockerfile makes use of the opentelemetry-cpp packages in edge/testing (https://pkgs.alpinelinux.org/packages?name=opentelemetry-*&branch=edge&repo=testing&arch=&maintainer=), which brings down the build time to below a minute on my x86 laptop since all that needs to be compiled is the currency service itself.

### CODE REVIEW

**Review by julianocosta89 — CHANGES_REQUESTED** [review]
When building this one, it builds, but once I start the demo the currency service doesn't work. 
I'm getting the following in its logs:
```
currency-service  | Port: 7001
currency-service  | Assertion failed: false && "i == variant_npos" (/usr/include/opentelemetry/nostd/internal/absl/types/internal/variant.h: operator(): 426)
```

**Comment by svrnm** [comment]
> When building this one, it builds, but once I start the demo the currency service doesn't work. I'm getting the following in its logs:
> 
> ```
> currency-service  | Port: 7001
> currency-service  | Assertion failed: false && "i == variant_npos" (/usr/include/opentelemetry/nostd/internal/absl/types/internal/variant.h: operator(): 426)
> ```

Interesting, I didn't see that error when starting the currency service, let me check that. What arch did you use (x86_64 aarch64?)

**Comment by julianocosta89** [comment]
> Interesting, I didn't see that error when starting the currency service, let me check that. What arch did you use (x86_64 aarch64?)

amd64
WSL running Ubuntu 20.04

**Comment by austinlparker** [comment]
I'm seeing the same error on Apple Silicon (MacOS Ventura)

**Comment by svrnm** [comment]
that was not smart ... 🤦

**Comment by austinlparker** [comment]
Same problem, same system. ```Assertion failed: false && "i == variant_npos" (/usr/include/opentelemetry/nostd/internal/absl/types/internal/variant.h: operator(): 426)```

**Comment by svrnm** [comment]
> Same problem, same system. `Assertion failed: false && "i == variant_npos" (/usr/include/opentelemetry/nostd/internal/absl/types/internal/variant.h: operator(): 426)`

I didn't fix anything yet, I just reset my branch and recovered from it 🤦‍♂️  ... I'll try to find some time the next few days to dig into that.

**Comment by svrnm** [comment]
Still need to find the time to fix this, just commenting to keep the PR open for now :)

**Pull request closed without merging**
