### PR TITLE
Improve build times for JS and PHP

### PR DESCRIPTION
**Pull request by austinlparker**
In support of #458, this PR is making an attempt to improve build times by optimizing gRPC libs where possible/easy.

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by puckpuck — APPROVED** [review]

**Comment by julianocosta89** [comment]
@austinlparker this PR broke the PHP traces.
No spans are being exported anymore.

**Comment by austinlparker** [comment]
That's weird, it worked locally.

**Comment by reyang** [comment]
Would folks be interested in a CI job which captures traces across all services as part of the integration test? (I think integration test which covers telemetry correctness is an amazing thing to demonstrate, seems a good fit)

**Comment by austinlparker** [comment]
Yeah, that’d be good if we could get build times down… I don’t think it’s reasonable until then though. Sent from my iPhoneOn Nov 2, 2022, at 7:25 PM, Reiley Yang ***@***.***> wrote:﻿
Would folks be interested in a CI job which captures traces across all services as part of the integration test? (I think integration test which covers telemetry correctness is an amazing thing to demonstrate, seems a good fit)

**Pull request merged**
