### PR TITLE
update collector to build image using ocb

### PR DESCRIPTION
**Pull request by codeboten**
# Changes

The collector in this repository now uses the otel collector builder to build a custom binary which it embeds in a docker container for the demo.

Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/871

Still to do:

- [x] update curl command to pull builder for specific architectures
- [x] allow passing the version of the builder to use

Please provide a brief description of the changes here.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by austinlparker** [comment]
This is great! We'll need to make sure there's associated changes in docs and helm for it I believe.

**Comment by austinlparker** [comment]
heya - wanted to check in on this. we'd like to release 1.5 soonish and i'd like this in

**Comment by codeboten** [comment]
> heya - wanted to check in on this. we'd like to release 1.5 soonish and i'd like this in

Finally got back to this, i've updated the dockerfile to support build args for arch/builder version.

**Review by austinlparker — APPROVED** [review]
Looks great! One important note (i'll make a followup issue on this) is that this _will_ break anyone that's been using the collector contrib image for their demos.

**Pull request merged**
