### PR TITLE
Generating protobuf at container build time

### PR DESCRIPTION
**Pull request by fsolleza**
# Changes

Problem:

Small changes to protobuf require extensive tooling to generate protobuf using `make generate-protobuf`. `ide-gen-proto.sh` shows how _some_ service's protobuf might be generated.

Four services' generated protobuf code were moved to container build time. This doesn't replace `make generate-protobuf` which is still useful when understanding the protobuf code outside of build time. It makes `make start` and friends friendlier to small changes to `pb/demo.proto`.

The four services affected are:
1. accountingservice
2. checkoutservice
3. productcatalogservice
4. currencyservice

Solution is discussed in-depth in https://github.com/open-telemetry/opentelemetry-demo/issues/1374

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by puckpuck** [comment]
@fsolleza please sign the CLA when you get a chance

**Comment by fsolleza** [comment]
Hmm - I'm unfamiliar with this process but I've signed the CLA (or so I think).

**Comment by austinlparker** [comment]
Seems like there's still an issue with the CLA (see https://github.com/open-telemetry/opentelemetry-demo/pull/1384#issuecomment-1948513758) -- is the email associated with the commits different than the one that you signed the CLA with? You may need to squash your commits locally and force push the branch to resolve this.

**Comment by fsolleza** [comment]
Ok, I'm gonna retry with another pull request with hopefully the correct email address. It's small enough to easily just recreate from a clean branch tracking upstream.

**Pull request closed without merging**
