### PR TITLE
Opentelemetry Collector Data Flow Dashboard Preview

### PR DESCRIPTION
**Pull request by devrimdemiroz**
# Changes

A dashboard that shows Data Flow on Opentelemetry Collector over demo app.

DarkBluesCluttered
WhiteKnightCluttered

## Merge Requirements

Waiting feedback and corrections ...

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]

### CODE REVIEW

**Comment by austinlparker** [comment]
Interesting - couple of notes from running it locally:

- The span export ratio seems fine, but the metric export ratio seems strange? 
- Some more notes/annotations in the dashboard about what the actual metrics are measuring would be great.

This seems like a really good resource for people to learn about how to monitor pipelines.

**Comment by devrimdemiroz** [comment]
> Interesting - couple of notes from running it locally:
> 
> * The span export ratio seems fine, but the metric export ratio seems strange?
> * Some more notes/annotations in the dashboard about what the actual metrics are measuring would be great.
> 
> This seems like a really good resource for people to learn about how to monitor pipelines.

The export ratio visibility idea belongs to @jpkrohling . And it is indeed great so that you can spot something is **strange**. The particular thing about opentelemetry demo app is that the spanmetrics configuration makes it **strange**.  As it loops back within the collector configuration and does not exist among metrics incoming under otelcol_* namespace.

[otelcol metrics spreadsheet](https://docs.google.com/spreadsheets/d/183pNgoZqcFARcP3JJ_fbb7KYieLWeP2x1HCp8LNYu-Y/edit?usp=sharing) I deep dived into what is coming. This list also has memory_delimiter, servicegraph processor and more in it. Maybe with the new connector system upcoming inside the collector, it might be better. However, it is good to know it is **strange**. 🤓 

I have [this](https://tractatus.one/otelcol-metrics-pipeline-3d161983b5b9) as a base for a documentation. I can convert it into a markdown format.

**Comment by cartersocha** [comment]
The dashboard looks great! 

Would it be possible to include the service source or slice some of these ingress metrics by attributes like that? Might be another dashboard haha

**Comment by devrimdemiroz** [comment]
> The dashboard looks great!
> 
> Would it be possible to include the service source or slice some of these ingress metrics by attributes like that? Might be another dashboard haha

Thanks! 
I noted as remarks [here](https://tractatus.one/otelcol-metrics-pipeline-3d161983b5b9), the labels are very limited. I agree.  Guess, enhancements on the collector side to be able to distinguish services and pipelines would be necessary.

**Comment by austinlparker** [comment]
Yeah, if you can get the docs for this into markdown we'd love to pull it into the next release.

**Comment by julianocosta89** [comment]
@devrimdemiroz could you add a changelog entry?

**Review by julianocosta89 — COMMENTED** [review]
Please add a `changelog`.

**Review by julianocosta89 — APPROVED** [review]
LGTM 🤩

**Review by fatsheep9146 — APPROVED** [review]
Awesome

**Comment by devrimdemiroz** [comment]
Thank you for the great comments! 🥳 I hope it will help showcase the value of the OpenTelemetry Collector and make the demo application even more impressive.

**Comment by devrimdemiroz** [comment]
Documentation PR --> https://github.com/open-telemetry/opentelemetry.io/pull/2535

**Comment by devrimdemiroz** [comment]
Documentation merged on this one https://github.com/open-telemetry/opentelemetry.io/pull/2569

**Pull request merged**
