### PR TITLE
[paymentservice] [checkoutservice] introduce new featureflags

### PR DESCRIPTION
**Pull request by EislM0203**
# Changes

This PR is an updated version of #1383 to conform to the updated feature flags. Also a comment regarding the `paymentServiceUnreachable` feature flag was addressed by moving the feature flag to the checkout-service. 

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate documentation updates in the [docs](https://github.com/open-telemetry/opentelemetry.io/pull/4142)
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by EislM0203** [comment]
Hello, as stated above this PR is the updated version of #1383. Sadly it seems like the helm chart is still outdated and I do not see any open PRs addressing that. Can you tell me what the status is there?

**Comment by julianocosta89** [comment]
> Hello, as stated above this PR is the updated version of #1383. Sadly it seems like the helm chart is still outdated and I do not see any open PRs addressing that. Can you tell me what the status is there?

Excelent question!
I'll take a look into it.

**Review by austinlparker — APPROVED** [review]

**Comment by julianocosta89** [comment]
> Hello, as stated above this PR is the updated version of #1383. Sadly it seems like the helm chart is still outdated and I do not see any open PRs addressing that. Can you tell me what the status is there?

There you go: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1082

**Comment by EislM0203** [comment]
> There you go: [open-telemetry/opentelemetry-helm-charts#1082](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1082)

@julianocosta89, thanks a lot for the info, as soon as this PR is merged I will make the changes to the helm chart. 

Also, do you perchance know why the `tracetesting` check is failing? I am asking because I made sure to check that it passes locally (see image). Would appreciate your insights.  
Screenshot 2024-03-14 at 08 58 25

**Comment by julianocosta89** [comment]
> Also, do you perchance know why the `tracetesting` check is failing? I am asking because I made sure to check that it passes locally (see image). Would appreciate your insights.

Testing out your PR, I did see the failing test.
It seems that the folks from TraceTest changed the name of the trigger and the test wasn't found.
Not related to your PR, but since the update of traceTest you are the first one to touch `checkoutService`.

I added the fix to your PR, hope you don't mind.

**Pull request merged**
