### PR TITLE
Added Kloudfuse

### PR DESCRIPTION
**Pull request by ashishkf**
# Changes

Added Kloudfuse

### CODE REVIEW

**Review by fatsheep9146 — CHANGES_REQUESTED** [review]
The list is alphabetical sorted, I think Kloudfuse should be next to Instana

**Comment by ashishkf** [comment]
> The list is alphabetical sorted, I think Kloudfuse should be next to Instana

done.

**Review by fatsheep9146 — APPROVED** [review]

**Comment by fatsheep9146** [comment]
@ashishkf could you help check the failed markdown lint?
https://github.com/open-telemetry/opentelemetry-demo/actions/runs/4350363256/jobs/7601470969

**Comment by ashishkf** [comment]
> @ashishkf could you help check the failed markdown lint?
> https://github.com/open-telemetry/opentelemetry-demo/actions/runs/4350363256/jobs/7601470969

done.

**Review by mviitane — APPROVED** [review]

**Comment by jack-berg** [comment]
This commit removed New Relic from the list. Can the New Relic entry be restored?

**Comment by ashishkf** [comment]
https://github.com/open-telemetry/opentelemetry-demo/pull/778

**Pull request merged**
