### PR TITLE
Add Business Metric Service

### LINKED ISSUE #850: New Service: Business Metric Processor
We need a new service to demonstrate a couple of concepts:
- Injecting instrumentation using k8s operator
- Custom Java metrics/logs

My suggestion would be for a small Java app that consumes the orders topic then creates new metrics displaying sales/hour, etc. ("business" metrics). However, there would be no OpenTelemetry instrumentation added to the container, it would only be added through operator injection.

### PR DESCRIPTION
**Pull request by austinlparker**
# Changes

Closes #850 

This adds a Java service that deliberately does _not_ enable OpenTelemetry instrumentation at build time. It only takes a dependency on the OpenTelemetry API to create a metric. The intended use of this service is to demonstrate the OpenTelemetry Operator's Instrumentation CRDs (as well as API-only usage of OpenTelemetry).

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Comment by julianocosta89** [comment]
Are we adding a new java service?
Wouldn't be better to allow users to enable/disable instrumentation on the services we already have?

**Comment by cartersocha** [comment]
I'm hesitant to add to the existing resource requirements given the kubecon feedback for a smaller footprint

**Comment by julianocosta89** [comment]
> I'm hesitant to add to the existing resource requirements given the kubecon feedback for a smaller footprint

same here

**Comment by austinlparker** [comment]
I don't anticipate this being used in a local deployment -- my 0.02 is that we should address the resource issue by creating a "minimal" set of services to be run locally while allowing for a larger set to be run in "production" deployments

**Comment by austinlparker** [comment]
The advantage of adding a net new service here is that it's a terminal/leaf service, ensuring that disabling the service or running it without instrumentation doesn't impact the rest of the deployment.

**Comment by puckpuck** [comment]
Let's create a plan to have minimal and more expansive deployment scenarios before we add anything new.  Something we can discuss in detail at the next SIG meeting.

**Comment by cartersocha** [comment]
Can merge post simple+ demo

**Comment by austinlparker** [comment]
I'll be able to publicly share the demo flow for this in a few weeks

**Comment by puckpuck** [comment]
After we get #872 finished and merged, we can look to move this as an additional service in an optional module/preset.

**Pull request closed without merging**
