### PR TITLE
rename proto package from hipstershop to oteldemo

### LINKED ISSUE #638: Remove "hipstershop" from Proto definition
The OpenTelemetry demo is now associated with a space exploratory theme that does not fit the original name (and namespace) associated with the original GCP hipstershop project theme that formed the original basis for this demo.

Renaming the `hipstershop` namespace in the protobuf definition will have an effect on all services, and such a change should be taken with proper care.

### PR DESCRIPTION
**Pull request by codeboten**
# Changes

Renames the proto definition package to oteldemo. Wanted to see how much work was involved here, open to alternative names. Figured oteldemo was short and to the point :)

Fixes #638

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/

### CODE REVIEW

**Comment by cartersocha** [comment]
We'll need a changelog entry too. 

Thanks for doing this @codeboten

**Comment by codeboten** [comment]
Updated the changelog, although i found it confusing that the changelog doesn't match w/ the release notes. I added headers to separate the released versions from what wasn't released.

Tested this locally, looks good 👍🏻 
Screen Shot 2023-02-10 at 8 48 55 AM

**Review by julianocosta89 — COMMENTED** [review]
It looks great!
Thx for taking care of this @codeboten!

I haven't approved bc I couldn't test (currently on my phone), but will build and run it later.

Also, thx for the update on the changeling, it looks way more organised now!

**Review by cartersocha — APPROVED** [review]
lgtm

**Review by julianocosta89 — APPROVED** [review]
Tested locally and everything is working as expected. 🚀

**Pull request merged**
