### PR TITLE
(jaeger): Fix jaeger span metrics

### PR DESCRIPTION
**Pull request by puckpuck**
# Changes

Fixes: #864 

Adds proper command args to Jaeger to understand the proper metric names generated from the `spanmetrics` connectors.

## Merge Requirements

* [x] `CHANGELOG.md` updated to document new feature additions
* [x] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Review by julianocosta89 — APPROVED** [review]
LGTM

**Comment by julianocosta89** [comment]
@puckpuck just one question, what is the file: `src/prometheus/prometheus-config.yaml` that is empty but shouldn't be removed?

**Comment by puckpuck** [comment]
> @puckpuck just one question, what is the file: `src/prometheus/prometheus-config.yaml` that is empty but shouldn't be removed?

Prometheus will error out if a config file is not passed into the startup, since the default image does not have one. Typically Prometheus is used to pull metrics, so a config will always be present, but since we are using it only in a push method, we don't have a scraping config to pass in.

```
prometheus  | ts=2023-10-20T03:47:16.236Z caller=main.go:487 level=error msg="Error loading config (--config.file=prometheus.yml)" file=/prometheus/prometheus.yml err="open prometheus.yml: no such file or directory"
```

**Comment by austinlparker** [comment]
Turns out this file was _kinda_ important as it was scraping collector metrics. Removing it broke the collector dashboard in Grafana.

**Pull request merged**
