### PR TITLE
[grafana] Add Exemplars Dashboard

### PR DESCRIPTION
**Pull request by julianocosta89**
# Changes

Companion PR of https://github.com/open-telemetry/opentelemetry-demo/pull/1830.
This PR adds a Dashboard to Grafana to view Exemplars added to CartService.

## Merge Requirements

For new features contributions, please make sure you have completed the following
essential items:

* [x] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs][]
* [ ] Appropriate Helm chart updates in the [helm-charts][]

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

[docs]: https://opentelemetry.io/docs/demo/
[helm-charts]: https://github.com/open-telemetry/opentelemetry-helm-charts

### CODE REVIEW

**Comment by puckpuck** [comment]
I found that the exemplar links to Jaeger would result in not-found traces because they expired out of Jaeger too quickly. Only after manually increasing Jaeger's capacity in docker-compose was I able to get the links to work. To make this feature usable, we need to give Jaeger more trace capacity and memory limits.

This is likely for another issue, but we may want to examine the telemetry load as a whole within the context of the demo. There may be telemetry optimizations we could make, maybe even altering the load velocity so telemetry can live in memory longer before aging out due to memory limits.

**Comment by puckpuck** [comment]
I updated the dashboard in the example to better represent histogram metrics with exemplars.

I also made some changes to the load generator to reduce the number of users to 5, thus, reducing the number of traces per second going into Jaeger. I also increased the memory for Jaeger to 1200M and the max traces to 25000. Together, this allows for about 10 mins worth of traces in Jaeger that can be linked to the recent exemplars in the Grafana dashboard.
Screenshot 2024-12-13 at 9 03 11 PM

**Review by puckpuck — APPROVED** [review]

**Comment by julianocosta89** [comment]
Oh wow!
This is awesome!

Thanks @puckpuck!!!

**Comment by CharlieTLe** [comment]
Very cool, thanks for setting this up. I did a talk at KubeCon about exemplars using this repo. It might be worth linking to for more info about how it works.

https://www.youtube.com/watch?v=zYF1JIZmpI4&list=PLj6h78yzYM2Pw4mRw4S-1p_xLARMqPkA7&index=136

**Comment by julianocosta89** [comment]
> Very cool, thanks for setting this up. I did a talk at KubeCon about exemplars using this repo. It might be worth linking to for more info about how it works.
> 
> 
> 
> https://www.youtube.com/watch?v=zYF1JIZmpI4&list=PLj6h78yzYM2Pw4mRw4S-1p_xLARMqPkA7&index=136

This is really cool!
Thanks for sharing @CharlieTLe 🤩🤩🤩

**Pull request merged**
