### PR TITLE
[loadgenerator] - rewrite for new frontend and feature flags

### PR DESCRIPTION
**Pull request by puckpuck**
## Changes

A major rewrite of the load generator to incorporate 3 big changes

1. Work with the update routes defined by the frontend service rewrite
2. Add multiple random "people" to the checkout call, to work with a future feature flag
3. Update to use locust test suite `@task` annotations

The recently updated frontend service meant some changes to the load generator. Namely, there is no more `set_currency` load since that route no longer exists. The `cart` and `checkout` loads were updated to match what the new frontend service has in place.

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes

### CODE REVIEW

**Comment by mviitane** [comment]
Suggesting an update for the commit message:
"A major rewrite of the frontend service"
->
"A major rewrite of the load generator"

**Comment by mviitane** [comment]
When running the updated loadgen, I can see the following in the log:
```
cart-service             | AddItemAsync called with userId=199d832e-1a2a-11ed-8863-0242c0a80013, productId=OLJCESPC7Z, quantity=1
cart-service             | GetCartAsync called with userId=199d832e-1a2a-11ed-8863-0242c0a80013
checkout-service         | {"message":"[PlaceOrder] user_id=\"199d832e-1a2a-11ed-8863-0242c0a80013\" user_currency=\"USD\"","severity":"info","timestamp":"2022-08-12T10:32:43.922355684Z"}
cart-service             | GetCartAsync called with userId=199d832e-1a2a-11ed-8863-0242c0a80013
frontend                 | Error: 13 INTERNAL: failed to prepare order: failed to convert price of "OLJCESPC7Z" to USD
frontend                 |     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
frontend                 |     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
frontend                 |     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
frontend                 |     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
frontend                 |     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
frontend                 |     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
frontend                 |   code: 13,
frontend                 |   details: 'failed to prepare order: failed to convert price of "OLJCESPC7Z" to USD',
frontend                 |   metadata: Metadata {
frontend                 |     internalRepr: Map(1) { 'content-type' => [Array] },
frontend                 |     options: {}
frontend                 |   }
frontend                 | }
```

**Comment by mviitane** [comment]
> When running the updated loadgen, I can see the following in the log:

After building with --no-cache option the error is gone. Loadgen seems to be running fine now.

**Review by mviitane — APPROVED** [review]

**Comment by GaryPWhite** [comment]
confirmed -- this seems to work well for me too!

**Comment by cartersocha** [comment]
@puckpuck update (🙄) & merge at your leisure 🏎

**Review by mic-max — APPROVED** [review]

**Pull request merged**
